.changeset/new-seahorses-drive.md, .changeset/silly-dogs-marry.md, keystatic/CHANGELOG.md, keystatic/package.json
Reverts Thinkmill/keystatic#8
There was a problem with publishing that might take little bit to fix so I'm reverting the versioning.
=> Revert "Version Packages"

.changeset/sharp-cats-learn.md, design-system/packages/overlays/package.json, design-system/packages/overlays/src/Modal.tsx, design-system/packages/overlays/src/Overlay.tsx, design-system/packages/overlays/src/Popover.tsx, design-system/packages/overlays/src/Tray.tsx, design-system/packages/overlays/src/types.ts, design-system/packages/overlays/stories/Popover.stories.tsx, design-system/packages/overlays/test/Overlay.test.tsx, design-system/packages/tooltip/src/Tooltip.tsx, design-system/packages/tooltip/src/TooltipTrigger.tsx, design-system/packages/tooltip/src/context.ts, design-system/packages/tooltip/stories/TooltipTrigger.stories.tsx, pnpm-lock.yaml
Resolves #120
Provide `nodeRef` to overlay components. Fixes `findDOMNode` errors in StrictMode.
[Discussion on react-transition-group](https://github.com/reactjs/react-transition-group/issues/668).
=> Refactor overlays

keystatic/local-config.tsx, packages/keystatic/DocumentEditor/component-blocks/fields/date.tsx, packages/keystatic/DocumentEditor/component-blocks/fields/image.tsx, packages/keystatic/DocumentEditor/component-blocks/fields/integer.tsx, packages/keystatic/DocumentEditor/component-blocks/fields/pathReference.tsx, packages/keystatic/DocumentEditor/component-blocks/fields/relationship.tsx, packages/keystatic/DocumentEditor/component-blocks/fields/url.tsx, packages/keystatic/DocumentEditor/component-blocks/fields/utils.tsx, packages/keystatic/reader.test.tsx
This adds `validation.isRequired` to the following fields (all other fields can never be null):
- `relationship`
- `pathReference`
- `integer`
- `date`
- `image`
- `url`
When you specify `validation.isRequired`, the types from the reader API will reflect that they can never be null.
This also adds `validation.min` and `validation.max` to `integer` and `date.
=> More field validation

.changeset/dry-feet-report.md, .changeset/polite-falcons-drum.md, apps/next-pages-dir/local-config.tsx, apps/remix/local-config.tsx, keystatic/local-config.tsx, packages/keystatic/app/CollectionPage.tsx, packages/keystatic/app/ItemPage.tsx, packages/keystatic/app/path-utils.ts, packages/keystatic/app/required-files.ts, packages/keystatic/app/shell/data.tsx, packages/keystatic/app/tree-key.tsx, packages/keystatic/app/useItemData.ts, packages/keystatic/app/useSlugsInCollection.ts, packages/keystatic/app/utils.ts, packages/keystatic/config.tsx, packages/keystatic/src/api/read-local.ts, packages/keystatic/src/reader.ts, packages/keystatic/utils.tsx
This allows having files like  `collection/slug.{yaml,json,mdoc}` instead of `collection/slug/index.{yaml,json,mdoc}` which is especially nice when you don't have any other files which would be in the directory.
=> Allow having data files outside of their entry directories

.changeset/eighty-knives-sort.md, apps/astro/keystatic.config.tsx, apps/localization/src/config.ts, apps/next-pages-dir/local-config.tsx, apps/remix/local-config.tsx, keystatic/local-config.tsx, packages/keystatic/app/path-utils.ts, packages/keystatic/app/utils.ts, packages/keystatic/config.tsx
This replaces the `directory`, `directorySuffix` and `format.location` options with a new `path` option that's less confusing.
- In collections, `path` must include a `*` which indicates where in the path the slug should go (the default is `collection-name/*/`)
- in singletons, `path` must not include a `*` (the default is `singleton-name/`)
- if the path ends with a trailing slash, the structure will look like this:
- `something`
- `slug`
- `index.yaml`
- `other.mdoc`
- if the path doesn't end in a trailing slash, the structure will look like this:
- `something`
- `slug.yaml`
- `slug`
- `other.mdoc`
=> Path option

.changeset/unlucky-jars-divide.md, packages/keystatic/app/shell/index.tsx, packages/keystatic/app/utils.ts, packages/keystatic/config.tsx
TypeScript doesn't like `{ a: { kind: 'a' } } | { a: { kind: 'b' } }`
=> Fix conditional storage

.changeset/perfect-flowers-build.md, .changeset/wet-socks-rest.md, keystatic/local-config.tsx, packages/keystatic/DocumentEditor/component-blocks/api.tsx, packages/keystatic/DocumentEditor/component-blocks/fields/array.tsx, packages/keystatic/DocumentEditor/component-blocks/fields/checkbox.tsx, packages/keystatic/DocumentEditor/component-blocks/fields/date.tsx, packages/keystatic/DocumentEditor/component-blocks/fields/document.tsx, packages/keystatic/DocumentEditor/component-blocks/fields/image.tsx, packages/keystatic/DocumentEditor/component-blocks/fields/integer.tsx, packages/keystatic/DocumentEditor/component-blocks/fields/multiselect.tsx, packages/keystatic/DocumentEditor/component-blocks/fields/pathReference.tsx, packages/keystatic/DocumentEditor/component-blocks/fields/relationship.tsx, packages/keystatic/DocumentEditor/component-blocks/fields/select.tsx, packages/keystatic/DocumentEditor/component-blocks/fields/url.tsx, packages/keystatic/DocumentEditor/component-blocks/form-from-preview.tsx, packages/keystatic/app/provider.tsx, packages/keystatic/markdoc/find-children.test.ts
- Adds `description` to all the other fields
- Skip attempting to get a GitHub auth token when using local mode (note this never caused a redirect or anything previously, it just did an unnecessary request to the API route to try getting a refreshed auth token)
=> Little fixes

packages/keystatic/DocumentEditor/table.tsx
Small tweaks to fix the table layout styles, so that
* The table outline sits nearly within the document margins
* Cell content is vertically-aligned to the top, and doesn't jump the first time you add a second line
* Cells have padding
Some magic numbers in here, but I think it's OK for now.
Screenshot after:
=> Fix editor table styles

.prettierignore
Otherwise adding a changeset with the changesets bot fails the format test on CI.
Probably not the _best_ solution (ideally the bot would be configurable?) but without this, the GitHub workflow is pretty awkward.
Happy for a different solution if you have one @emmatown
=> Ignore changesets with prettier

.changeset/bright-schools-reply.md, packages/keystatic/DocumentEditor/table.tsx
Cosmetic fixes for RTL:
| Before | After |
|--------|-------|
| ![before screenshot](https://user-images.githubusercontent.com/2730833/226276097-bfd619da-03e1-4a3f-ba3a-f7302e18be91.png) | ![after screenshot](https://user-images.githubusercontent.com/2730833/226276188-5f1ed144-58c5-4c09-ad9d-6855c25905d1.png) |
Still need to review other things like "Insert columns right" etc.
**Related:**
- hide cell selection buttons unless table selected: some affordance that they're interactive
- smaller cell menu trigger: reduce how frequently they clash with text
=> Editor table RTL

.changeset/popular-actors-deliver.md, keystatic/local-config.tsx, package.json, packages/keystatic/DocumentEditor/Toolbar.tsx, packages/keystatic/DocumentEditor/component-blocks/fields/document.tsx, packages/keystatic/DocumentEditor/component-blocks/form-from-preview.tsx, packages/keystatic/DocumentEditor/component-blocks/index.tsx, packages/keystatic/DocumentEditor/component-blocks/utils.ts, packages/keystatic/DocumentEditor/document-features.ts, packages/keystatic/DocumentEditor/image.tsx, packages/keystatic/DocumentEditor/index.tsx, packages/keystatic/DocumentEditor/insert-menu.tsx, packages/keystatic/DocumentEditor/layouts.tsx, packages/keystatic/DocumentEditor/tests/utils.tsx, packages/keystatic/DocumentEditor/toolbar-state.tsx, pnpm-lock.yaml
This lets you add a title field(serialised to the normal markdown title syntax) to the built-in image block and also customise the alt text field to e.g. have a custom description. If a `title` field isn't provided, there won't be a title field in the UI (though a title written in the markdoc file will be valid and will be kept upon saving). If an `alt` field isn't provided, a default one will be used. Currently this doesn't allow arbitrary fields on images, though that will likely exist in the future.
=> Image block schema

.changeset/wild-cars-fix.md, design-system/packages/dialog/src/index.ts, design-system/packages/table/src/TableView.tsx, design-system/packages/table/src/index.ts, design-system/packages/table/src/styles.tsx
Fix `TableView` overflow mode behaviour. Cell content may "wrap" and will be center-aligned only when `overflowMode` is "truncate". When providing complex children (non-string/number) consumers must implement their own truncation, using the `Text` component.
=> Table overflow mode

.changeset/slow-spoons-travel.md, packages/keystatic/DocumentEditor/component-blocks/api.tsx, packages/keystatic/reader.test.tsx, packages/keystatic/src/reader.ts
This makes using the reader API easier for a lot of common uses. (e.g. `all` for getting slugs with titles for navigation and `resolveLinkedFiles` for when you're rendering a blog post and you know you'll definitely need everything in the entry)
=> Add an all method to the collection reader API and `resolveLinkedFiles` option to the methods that read entries

.changeset/pretty-baboons-dress.md, keystatic/local-config.tsx, packages/keystatic/src/app/useItemData.ts, packages/keystatic/src/form/api.tsx, packages/keystatic/src/form/errors.ts, packages/keystatic/src/form/fields/array.tsx, packages/keystatic/src/form/fields/document/markdoc/find-children.test.ts, packages/keystatic/src/form/form-from-preview.tsx, packages/keystatic/src/form/parse-props.ts, packages/keystatic/src/form/validate-array-length.ts, packages/keystatic/src/reader.ts
This is non-parse-blocking validation just like `validation.length` on `fields.text`
=> Add `validation.length` to `fields.array`

docs/src/content/pages/installation-astro.mdoc
One of the code examples (docs) in the Astro integration guide is missing the frontmatter backticks, making it invalid code in a `.astro` file.
=> Add the frontmatter triple ticks in Astro guide import

docs/src/content/pages/installation-astro.mdoc
Without Astro's ´-- --host´flag keystatic won't display at localhost:3000/keystatic and throws multiple react errors. Using the flag fixes the problem.
Without importing keystaticConfig in the ´Displaying Keystatic content on the frontend ´section you get a reference error as keystaticConfig is undefined in the file.
=> Bugfixes Astro guide 

docs/src/content/pages/fields/document.mdoc
This information isn't really useful or relevant to users and I want the superscript gone so I can test the new editor on the docs content and currently it's not possible to implement stuff like that in the new editor
=> Remove superscript and references to the framework that the editor is using from docs

packages/keystatic/src/api/read-local.ts
Always ignore `.next` in returning local trees just like node_modules
=> Always ignore `.next` in returning local trees just like node_modules

docs/next-env.d.ts, docs/src/components/button.tsx, docs/src/components/copy-command-button.tsx, docs/src/components/hero.tsx, docs/src/content/pages/quick-start.mdoc, docs/src/utils/index.ts
- Adds "Copy command" button to homepage hero
- Adds CLI command and small content to /docs/quick-start page
=> KEY-154: CLI content

docs/src/components/document-renderer.tsx, docs/src/content/pages/introduction.mdoc
- Shifted some things around ("Good for" before "What you get")
- Removed some (imo) unnecessary copy to make it cleaner and easier to scan
- Fixed a broken link
- Increased font-weight of links in the readme's for increased visibility
=> Minor updates to /docs/introduction

docs/keystatic.config.tsx, docs/package.json, pnpm-lock.yaml
This adds a new collection to the keystatic config for the docs site using the new (very experimental) markdoc field but keeps the existing collection so everything will still work as it currently does.
For people working on the docs site rn: this will still be broken in various ways and isn't ready for you all to test just yet, I'm just getting this in because it makes it easier for me to test stuff.
=> Add markdoc field to the docs site for testing

.changeset/poor-poets-rhyme.md, design-system/packages/text-field/src/TextFieldPrimitive.tsx, packages/keystatic/src/form/fields/document/DocumentEditor/index.tsx
Minor fixes:
- more vertical padding on `TextArea` component
- antialiased editor text, to match the rest of the app
=> Text input paper cuts

.changeset/heavy-moose-bow.md, apps/localization/src/config.ts, packages/keystatic/src/app/l10n/locales.ts, packages/keystatic/src/app/provider.tsx, packages/keystatic/src/config.tsx
Closes #402 
Adds support for a new config key `locale` which must be one of the supported locales.
Defaults to `en-US` for now (see #401 for reason)
Also adds a containing `div` with locale `lang` and `direction` per https://react-spectrum.adobe.com/react-aria/internationalization.html#example
=> Configure locale

package.json
If you get an error because of this, make sure you're using https://nodejs.org/api/corepack.html
It should be as simple as unstinstalling however you installed pnpm previously and then `corepack enable pnpm`
=> Enforce pnpm version

.changeset/tiny-carrots-hug.md, design-system/pkg/src/number-field/NumberField.tsx
I'm not sure why these weren't passed before
In the `TextField` component, `...props` is spread, but in `NumberField` props is spread as `{...filterDOMProps(props)}`
This means the `description` and `label` props weren't being passed, despite being in the types and supported by the `TextFieldPrimitive` component.
@jossmac might be worth you taking a look at for consistency, but in the meantime this fixes #426
=> Add label and description to number field

.changeset/honest-ghosts-chew.md, design-system/pkg/src/table/TableView.tsx, design-system/pkg/src/table/types.ts, packages/keystatic/src/app/CollectionPage.tsx, packages/keystatic/src/app/ItemPage.tsx, packages/keystatic/src/app/entry-form.tsx, packages/keystatic/src/app/shell/header.tsx, packages/keystatic/src/app/shell/index.tsx, packages/keystatic/src/app/shell/panels.tsx, packages/keystatic/src/app/shell/topbar.tsx
Adhere to Figma designs (as best as possible) and tidy some things:
- Collection page: render empty state when no results from search
- Item page: fix bug where a single column layout flashes when `entryLayout=content` on desktop
=> Desktop spacing

.changeset/stupid-geckos-sniff.md, design-system/pkg/src/number-field/StepButton.tsx, design-system/pkg/src/text-field/TextFieldPrimitive.tsx, design-system/pkg/src/text-field/stories/TextField.stories.tsx
Refactor the field primitive interaction model—fixes a bug where non-interactive adornments block pointer events on the perceived input bounding rect.
**Some context:**
It might seem like a good idea to have the input fill the container and layer absolutely positioned adornments on top, but that requires insetting the input's inline padding. This is fine when you know the element's dimensions ahead of time, but in cases where the adornment is dynamic, e.g. localised strings, you're forced to do awkward and often poorly performing measurements at runtime. Another benefit of this approach is that adornments avoid conflict with third-party extensions like password managers.
=> Field adornment fixes

.changeset/long-apricots-sort.md, design-system/pkg/src/button/ActionButton.tsx, design-system/pkg/src/button/Button.tsx, design-system/pkg/src/button/stories/ActionButton.stories.tsx, design-system/pkg/src/button/types.ts, design-system/pkg/src/button/useActionButtonStyles.tsx, design-system/pkg/src/button/useButtonStyles.tsx, design-system/pkg/src/editor/stories/EditorPopover.stories.tsx, design-system/pkg/src/link/TextLink/TextLinkAnchor.tsx, design-system/pkg/src/link/TextLink/types.ts, design-system/pkg/src/link/TextLink/useTextLink.ts, design-system/pkg/src/style/index.ts, design-system/pkg/src/style/responsive.ts, design-system/pkg/src/types/dom.ts, packages/keystatic/package.json, packages/keystatic/src/app/ItemPage.tsx, packages/keystatic/src/app/dashboard/BranchSection.tsx, packages/keystatic/src/app/dashboard/CollectionSection.tsx, packages/keystatic/src/app/dashboard/DashboardPage.tsx, packages/keystatic/src/app/dashboard/SingletonSection.tsx, packages/keystatic/src/app/dashboard/components.tsx, packages/keystatic/src/app/shell/data.tsx, packages/keystatic/src/app/shell/i18n.tsx, packages/keystatic/src/app/shell/panels.tsx, packages/keystatic/src/app/shell/sidebar.tsx, packages/keystatic/src/app/shell/topbar.tsx, packages/keystatic/src/app/shell/viewer-data.ts, pnpm-lock.yaml
Update dashboard page to use card-like interface elements for collections and singletons.
Related app changes:
- declare side and main app panels as "inline-size" containers
- less obtrusive change indicators on sidebar singleton
- create `useLocalizedString` hook, which abstracts l10n message import to one location
Related component library changes:
- adjust `AnchorDOMProps` type; require "href" property and remove (MIME) "type" property
- support "href" (and friends) on `ActionButton` component
- expose `containerQueries` from "style" package
- fix class list declaration issue, which was causing a warning from `FieldButton` component
=> Dashboard UI update

.changeset/few-rockets-invite.md, packages/keystatic/src/app/shell/panels.tsx
This isn't a particularly big change or comprehensive fix or anything, but it's been annoying me that when I resize windows, the navigation sidebar always ends up too big and then I have to drag it smaller.
So after some tinkering (you're right @jossmac this is really fiddly) I ended up just reducing the maximums to make it "feel better". Let's shrink it and see if anyone comes up with a use-case for it to be meaningfully wider than the new max?
Otherwise it really eats into content entry space when you resize the window, on a normal 13" screen viewport.
**Before**:
**After**:
=> Update panel size max for sidebar

docs/src/content/pages/fields/document.mdoc
Small typo/inconsistency fix :)
Keep up the great work 🙌🏻
=> Fix incorrect `format` option of Documents in the docs

.changeset/spicy-seahorses-remember.md, packages/keystatic/src/app/dashboard/components.tsx
@jossmac continuing the riff on styling, agree with you the `accent` colour for borders on hover isn't quite where it's at, and I couldn't find anything else I prefer aesthetically than this.
If you're also "this is better", let's go with the `emphasis` token for now, and pick it up back in design with @tuan23
=> Update card hover style

dev-projects/astro-content/package.json
Just updating this so it's consistent with other `dev-project` packages, realised it was inconsistent when I was reviewing a changeset.
=> Rename astro-content package

.changeset/three-bears-weep.md
These changes were merged to `main` without a changeset, so catching up with this PR (and will review branch protection rules tomorrow!)
**TL;DR** I've updated the document field defaults, and the associated documentation, as mentioned in #531
This closes #504
I'd like to spend some more time with the docs to better explain how to set up custom tags in Markdoc properly if you opt into the (now-off) additional formatting options, so #531 remains open until then, but this means we have one less footman in the meantime.
=> Adding changeset for document field changes

docs/src/content/pages/how-keystatic-organises-your-content.mdoc
Improves and extends the documentation of the `path` option on singletons and collections.
Fixes https://github.com/Thinkmill/keystatic/issues/529
=> Content path and * wildcard documentation

.changeset/modern-clocks-reply.md, design-system/pkg/src/utils/ts/forwardRefWithAs.ts
Omit legacy attributes from `forwardRefWithAs` utility. Avoid issues like:
```jsx
<Flex color={string | undefined} />
```
=> Forward ref legacy attributes

.changeset/sharp-tools-bathe.md, docs/src/components/document-renderer.tsx, packages/keystatic/src/component-blocks/cloud-image-preview.tsx, packages/keystatic/src/component-blocks/cloud-image-schema.tsx
Fixes and improvements to the cloud image block:
- switch to `integer` for dimension attributes
- improve the appearance and UX of the dialog UI
- insert opens the dialog and reveals a simplified, non-interactive placeholder
- escape/cancel closes the dialog and removes the unused block (when no URL provided)
- minor aesthetic improvements to the image preview
=> Cloud image component block

packages/keystatic/src/component-blocks/cloud-image-preview.tsx
This fixes a bug where Firefox doesn't handle Slate focus as expected, and leaves the image placeholder.
It also adds some defensive text and a handler so you can clearly click on an image placeholder to bring up the dialog if you somehow end up with an invalid tag in your Markdoc document.
(and I removed the "no alt text" state, not a fan tbh)
@jossmac over to you for review, there may be better ways of handling this generally but this does make Firefox more robust for now.
=> Fix Firefox bug cleaning up cloud image components

packages/keystatic/src/app/CollectionPage.tsx
I noticed that since the latest UI refresh, we're showing "unchanged" status for all the collection items in the list view when in local mode (i.e `{ storage: { mode: 'local' } }`)
That's really misleading, so this PR fixes it.
tbh not my finest work, the layout (esp. with row columns) is pretty finicky but I couldn't pull the cells out into a separate component without messing around with types (i.e the type of `item` is just inferred from the scope, so specifying it as a prop type in another component is beyond me but I'd love to see how it's done)
I also added a flex container to the label cells matching the height of the `StatusLight` component because otherwise the rows squish up and it's not my intention that the layout actually changes in local mode.
So, happy to get advice on how …
=> Remove status column in collection view in local mode

packages/keystatic/src/component-blocks/cloud-image-preview.tsx
Simple fix to make the "edit image" modal show the Alt, Width and Height immediately; speeds up the workflow quite a bit.
The image URL is still requested in the background, which means that by the time you interact with the fields, the size detection works as expected.
=> Improve cloud image component editing

packages/keystatic/src/component-blocks/cloud-image-preview.tsx
Works in all browsers. Some undesirable cursor movement, but better than before.
=> cloud image component block deletion

.changeset/dull-ties-battle.md, packages/keystatic/src/app/shell/panels.tsx
Users may resize their window on larger devices to be below the "desktop" breakpoint, which previously caused a re-render of the entire tree. Avoid conditional rendering wherever possible, and strictly limit to leaf nodes when necessary.
=> Main panel layout

.changeset/seven-suits-train.md, packages/keystatic/src/component-blocks/cloud-image-preview.tsx, packages/keystatic/src/component-blocks/cloud-image.tsx, packages/keystatic/src/component-blocks/index.tsx, packages/keystatic/src/form/fields/cloudImage/ui.tsx
I was watching @lukebennett88 implement a `cloudImage` component block renderer in his site, and he had to guess/recreate this type in his front-end.
Seems better for us to export it and allow people to import the same definition we're using internally.
(I also consolidated the duplicate types between the component block and the field, since other code is also being shared)
=> Export CloudImageProps

docs/keystatic.config.tsx, docs/src/app/(public)/docs/[...slug]/page.tsx, docs/src/utils/reader.ts
This fixes the 404s in the docs website, and removes a duplicate `reader` creation.
Background:
* We updated the collection paths in production to get keystatic working when deployed from the monorepo
* However, the reader is basing its paths on `process.cwd()` which is _not_ expected to be the root of the monorepo
* This was causing the Reder to fail to find `.mdoc` files in collections that were found in development mode
=> Fix website reader path in production

docs/keystatic.config.tsx, docs/src/component-blocks/aside.tsx, docs/src/component-blocks/embed.tsx, docs/src/component-blocks/field-demo.tsx, docs/src/component-blocks/index.ts, docs/src/component-blocks/tags.tsx, docs/src/components/document-renderer.tsx, docs/src/content/pages/entry-layout.mdoc, docs/src/content/pages/fields/date.mdoc, docs/src/content/pages/fields/datetime.mdoc, docs/src/content/pages/fields/file.mdoc, docs/src/content/pages/fields/image.mdoc, docs/src/content/pages/fields/integer.mdoc, docs/src/content/pages/fields/multiselect.mdoc, docs/src/content/pages/fields/select.mdoc, docs/src/content/pages/fields/slug.mdoc, docs/src/content/pages/fields/text.mdoc, docs/src/content/pages/fields/url.mdoc, docs/src/content/pages/github-mode.mdoc
This cleans up our docs website config considerably.
* Component blocks are defined in their own files now, which makes the config easier to understand
* The old cloud images field has been removed the new one is compatible with the existing images (and I've updated the tags to use the new `src` prop, and integers for `width` and `height`)
* The `field-demo` tag casing is consistent with the other tags now
* The previews correctly use `NotEditable`
=> Website component blocks cleanup

docs/src/component-blocks/aside.preview.tsx, docs/src/component-blocks/aside.tsx, docs/src/component-blocks/embed.tsx, docs/src/component-blocks/field-demo.tsx, docs/src/component-blocks/tags.preview.tsx, docs/src/component-blocks/tags.tsx
Just some more minor refactoring for the docs site component blocks, now demonstrating how to separate the preview into a different file while still using the correct prop types.
=> More component blocks cleanup

.changeset/neat-waves-shout.md, design-system/pkg/src/style/index.ts
Reverts Thinkmill/keystatic#597
Adding `'use client'` to this is misleading, `@keystar/ui/style` won't work in a server components and adding `'use client'` doesn't change that
=> Revert "Add "use client" to style entrypoint in keystar-ui"

.changeset/shaggy-teachers-tickle.md, design-system/pkg/contextual-help/package.json, design-system/pkg/package.json, design-system/pkg/src/contextual-help/ContextualHelp.tsx, design-system/pkg/src/contextual-help/docs/index.md, design-system/pkg/src/contextual-help/index.ts, design-system/pkg/src/contextual-help/l10n.json, design-system/pkg/src/contextual-help/stories/ContextualHelp.stories.tsx, design-system/pkg/src/contextual-help/types.ts, design-system/pkg/src/field/FieldPrimitive.tsx, design-system/pkg/src/field/stories/Field.stories.tsx, design-system/pkg/src/field/types.tsx
New package "@keystar/ui/contextual-help" exposes `ContextualHelp` component. 
> Contextual help shows a user extra information about an adjacent component.
Support "contextualHelp" prop on field components, `Field` and `FieldPrimitive`.
=> Contextual help

.changeset/good-news-thank.md, packages/keystatic/src/app/ItemPage.tsx, packages/keystatic/src/app/entry-form.tsx, packages/keystatic/src/app/useItemData.ts, packages/keystatic/src/form/errors.ts, packages/keystatic/src/form/fields/array/ui.tsx, packages/keystatic/src/form/fields/conditional/ui.tsx, packages/keystatic/src/form/fields/date/index.tsx, packages/keystatic/src/form/fields/date/ui.tsx, packages/keystatic/src/form/fields/date/validateDate.tsx, packages/keystatic/src/form/fields/datetime/index.tsx, packages/keystatic/src/form/fields/datetime/ui.tsx, packages/keystatic/src/form/fields/datetime/validateDatetime.tsx, packages/keystatic/src/form/fields/integer/index.tsx, packages/keystatic/src/form/fields/integer/ui.tsx, packages/keystatic/src/form/fields/integer/validateInteger.tsx, packages/keystatic/src/form/fields/object/ui.tsx, packages/keystatic/src/form/fields/slug/index.tsx, packages/keystatic/src/form/fields/slug/ui.tsx, packages/keystatic/src/form/fields/text/index.tsx, packages/keystatic/src/form/fields/text/path-slug-context.tsx, packages/keystatic/src/form/fields/text/ui.tsx, packages/keystatic/src/form/fields/text/validateText.tsx, packages/keystatic/src/form/fields/url/index.tsx, packages/keystatic/src/form/fields/url/ui.tsx, packages/keystatic/src/form/fields/url/validateUrl.tsx, packages/keystatic/src/form/form-from-preview.tsx
Fixes #604
This doesn't resolve _all_ the circular dependencies because some would be less practical to remove but this seems to resolve the circular dependencies causing problems (from testing with a snapshot release: `@keystatic/core@0.0.0-test-20230831044006`)
=> Fix circular dependencies

.changeset/popular-moles-clap.md, design-system/pkg/src/tooltip/Tooltip.tsx, packages/keystatic/src/component-blocks/cloud-image-preview.tsx, packages/keystatic/src/form/fields/cloudImage/ui.tsx
Support constrained proportions on cloud image block and field. Refactor `Tooltip` styles to allow consumer overrides via style props.
=> Cloud image constrain proportions

.changeset/neat-walls-pump.md, packages/astro/src/api.tsx
Ref: https://thinkmill.slack.com/archives/C04CLQBUF29/p1693987161543119?thread_ts=1693982871.802299&cid=C04CLQBUF29
I'm not quite sure how the CommonJS output was used here but it was and that broke things because Preconstruct outputs `import.meta.whatever` as `undefined` in CommonJS (since `import.meta` is only an ESM thing and it can't really know what else to output there) so this try catches reading from `import.meta.env`
=> Fix `@keystatic/astro/api` CommonJS output

.changeset/odd-paws-exist.md, packages/astro/src/index.ts
This generates a file into `.astro` (since that will already be gitignored) with imports to Keystatic packages and tells Vite to look at it for discovering dependencies to pre-bundle which fixes the problem of getting errors from Vite trying to load CommonJS modules as ESM
I'm not going to update the template to use this just yet, I'd like to get this released first to make sure that it definitely works first (though from the snapshot release, it seems to)
Snapshot release for testing: `@keystatic/astro@0.0.0-test-20230907032149`, https://github.com/Thinkmill/keystatic/actions/runs/6105022202/job/16567883939#step:7:33
Fixes  #580
=> Fix astro integration

.changeset/rude-clocks-change.md, templates/astro/astro.config.mjs, templates/astro/keystatic.page.ts, templates/astro/src/pages/api/keystatic/[...params].ts, templates/astro/src/pages/keystatic/[...params].astro
#620 seems to work okay, so looks like we can use it here
=> Replace manually created pages for Keystatic with Astro integration that injects routes

.changeset/fifty-mayflies-matter.md, packages/keystatic/src/app/ItemPage.tsx, packages/keystatic/src/app/create-item.tsx
Here are some notes on this PR:
https://www.loom.com/share/0f8373c18c864a5ba5c213e538ffa157
=> Duplicate entry

docs/src/content/pages/content-organisation.mdoc
This is a simple misspelling but thought it would nevertheless be worth fixing.
=> Mispelling in content organization documentation

.changeset/brave-dingos-pay.md, docs/keystatic.config.tsx, docs/src/content/pages/content-organisation.mdoc, docs/src/utils/reader.ts, packages/keystatic/src/app/ItemPage.tsx, packages/keystatic/src/app/SingletonPage.tsx, packages/keystatic/src/app/create-item.tsx, packages/keystatic/src/app/path-utils.ts, packages/keystatic/src/app/shell/data.tsx, packages/keystatic/src/app/shell/path-prefix.tsx, packages/keystatic/src/app/updating.tsx, packages/keystatic/src/app/useData.ts, packages/keystatic/src/config.tsx
This simplifies using Keystatic in monorepos by scoping all paths to a particular directory
```js
export default config({
storage: {
kind: 'github',
repo: 'my-org/my-repo',
pathPrefix: 'somewhere/my-site'
},
collections: {
posts: collection({
label: 'Posts',
path: 'content/posts/*/',
// ...
})
},
})
```
=> Add `storage.pathPrefix` option

docs/src/app/layout.tsx, docs/src/app/og/route.tsx
1. Updating default og image (change of image path)
2. Simplifying the previous code implementation in the route file. Replacing complex layering of tiled background texture image over background svg, to simply a background png.
=> og image update

.changeset/hungry-yaks-dance.md, docs/keystatic.config.tsx, packages/keystatic/src/app/ItemPage.tsx, packages/keystatic/src/app/SingletonPage.tsx, packages/keystatic/src/config.tsx
This adds a `previewUrl` option to collections and singletons that adds a link to where a user should see the output for the entry. For collections, `{slug}` can be used in the string to interpolate the slug.
This also aligns the header buttons on singletons with collections
=> Add `previewUrl` option

.changeset/wicked-radios-tease.md, packages/keystatic/src/app/dashboard/BranchSection.tsx, packages/keystatic/src/app/shell/data.tsx, packages/keystatic/src/app/shell/topbar.tsx
=> Link to specific open pull request instead of search page of open pull requests

.changeset/new-rivers-sit.md, packages/keystatic/src/app/cloud-auth-callback.tsx
=> Center loading indicator on Keystatic Cloud auth callback page

.changeset/tiny-garlics-chew.md, packages/keystatic/src/component-blocks/blank-for-react-server.tsx, packages/keystatic/src/component-blocks/cloud-image-preview.tsx, packages/keystatic/src/component-blocks/cloud-image.tsx, packages/keystatic/src/form/api.tsx, packages/keystatic/src/form/fields/document/DocumentEditor/Toolbar.tsx
=> `toolbarIcon` option in component blocks

docs/src/content/pages/installation-astro.mdoc
All other code blocks have a file name, which makes it a lot easier to follow along. Those two did not. This PR adds the missing file name suggestions.
=> Docs: installation-astro.mdoc: Add file names to code blocks

docs/src/app/(public)/showcase/page.tsx
At the moment, the "View on Github" button on https://keystatic.com/showcase incorrectly links to the project's URL. It should instead link to the repository URL. This pull request fixes that.
=> Fix incorrect repo URL

.changeset/famous-mails-know.md, packages/keystatic/src/app/shell/data.tsx, packages/keystatic/src/app/useItemData.ts
This makes loading entries faster in public repos by using `raw.githubusercontent.com` to load files which is generally just faster than the blobs API we use otherwise and it doesn't have aggressive rate limits which means we don't need to provide an auth token so no CORS pre-flight requests are necessary which saves a whole round-trip. Of course since we're not providing an auth token, it only works for public repos. (we can't just always use it and provide an auth token because `raw.githubusercontent.com` doesn't respond to CORS pre-flight requests. It does have an alternative way of authenticating with short-lived tokens that go in the url but there isn't an API to explicitly generate them (it does seem like they're available in the `download_url` property of …
=> Use raw.githubusercontent.com to fetch files for public repos

design-system/docs/next.config.mjs, dev-projects/next-app/next.config.js, dev-projects/next-pages/.vscode/settings.json, dev-projects/next-pages/next-env.d.ts, dev-projects/next-pages/next.config.js, dev-projects/next-pages/package.json, dev-projects/next-pages/pages/api/keystatic/[[...params]].tsx, dev-projects/next-pages/pages/keystatic/[[...params]].tsx, dev-projects/next-pages/tsconfig-for-next/tsconfig.json, dev-projects/next-pages/tsconfig.json, pnpm-lock.yaml
I was trying to test some changes to make sure they wouldn't break using Keystatic in the Next pages directory and noticed we didn't have a dev project for it anymore
=> Add next pages dev project

.changeset/curly-cows-press.md, packages/astro/package.json, packages/astro/src/ui.tsx, packages/keystatic/src/app/router.tsx, packages/keystatic/src/app/ui.tsx, packages/next/src/ui/app.tsx, packages/next/src/ui/pages.tsx, packages/remix/src/ui.tsx, pnpm-lock.yaml
This improves performance of navigating around Keystatic by avoiding using different routers for each framework and instead has some minimal pushState & popstate handling in Keystatic itself. It's particularly good in the Next app directory because it avoids fetching the server component payload on each payload (that takes e.g. 300ms for me on https://keystatic.com/keystatic). It's a breaking change for the different framework packages since they need the newer version of `@keystatic/core`.
=> Use minimal router in `@keystatic/core` over different ones for each framework

.changeset/chatty-bags-relate.md, design-system/pkg/package.json
don't pin next.js peer dependency to exact version to avoid errors like:
```
 WARN  Issues with peer dependencies found
.
└─┬ @keystatic/core 0.1.9
└─┬ @keystar/ui 0.4.0
└── ✕ unmet peer next@14.0.0: found 14.0.1
```
=> Don't pin peer dependency to exact next.js version

.changeset/shy-rabbits-behave.md, design-system/pkg/src/checkbox/types.ts, design-system/pkg/src/field/types.tsx
The type `require("@react-types/shared").Validation` is now a generic. We don't need the other stuff, so just replace with inline types.
=> Field types

.changeset/pretty-jars-tickle.md, design-system/pkg/src/progress/ProgressCircle.tsx
Refactor `ProgressCircle` — split animation properties across elements to fix transform-origin issue in safari.
=> Progress circle animation

docs/src/content/navigation.yaml, docs/src/content/pages/cloud.mdoc, docs/src/content/pages/fields/cloud-image.mdoc
- Sets the new `new` badge to the Cloud page to indicate new content
- Adds documentation about creating a Keystatic Cloud account and setting up authentication
- Adds documentation about the Cloud image transforms via optional URL query parameters
- Adds introduction to the `cloudImage` field and the `CloudImage` componentBlock, which will both have documentation pages dressed up shortly after.
=> Fleshed out Keystatic Cloud documentation

.changeset/silent-gifts-beam.md, packages/keystatic/src/form/fields/markdoc/editor/autocomplete/insert-menu.tsx, packages/keystatic/src/form/fields/markdoc/editor/popovers/index.tsx, packages/keystatic/src/form/fields/markdoc/editor/schema.tsx
Support and populate "description" + "icon" on insert menu items. Default `adaptToViewport` to "stick" on editor popovers; should yield better results in most cases.
| Before | After |
|--------|--------|
| <img width="344" alt="insert menu before changes" src="https://github.com/Thinkmill/keystatic/assets/2730833/e5b83606-f87b-451d-b053-6920e1c61ded"> | <img width="336" alt="insert menu items with icon and description" src="https://github.com/Thinkmill/keystatic/assets/2730833/09481ee4-830e-4ea9-97c8-1e905b5c71dd"> |
=> ProseMirror insert menu decoration

.changeset/chilled-plums-warn.md, .changeset/eleven-dragons-whisper.md, design-system/pkg/src/editor/EditorPopover.tsx, design-system/pkg/src/editor/stories/EditorListbox.stories.tsx, design-system/pkg/src/editor/stories/EditorPopover.stories.tsx, packages/keystatic/src/form/fields/markdoc/editor/Toolbar.tsx, packages/keystatic/src/form/fields/markdoc/editor/autocomplete/autocomplete.tsx, packages/keystatic/src/form/fields/markdoc/editor/context.tsx, packages/keystatic/src/form/fields/markdoc/editor/index.tsx, packages/keystatic/src/form/fields/markdoc/editor/popovers/index.tsx, packages/keystatic/src/form/fields/markdoc/editor/popovers/reference.tsx
**@keystar/ui**
- Support "boundary" + "portal" props on `EditorPopover` component.
- Simulate clipping for portal'd popovers.
**@keystatic/core**
- Markdoc editor boundary respected by popovers.
- Markdoc editor popovers tethered to reference regardless of type (node/range/virtual) + better perf.
=> Editor popover improvements

docs/keystatic.config.tsx, docs/next.config.js, docs/src/app/(public)/resources/layout.tsx, docs/src/app/(public)/resources/page.tsx, docs/src/app/(public)/showcase/layout.tsx, docs/src/content/navigation.yaml, docs/src/content/resources/7-things-i-about-keystatic.yaml, docs/src/content/resources/codebase-editing-with-minimal-footprint.yaml, docs/src/content/resources/dinesh-pandiyan-markdoc-what-is-it-and-why-do-i-love-it.yaml, docs/src/content/resources/keystatic-the-last-framework-hop.yaml, docs/src/content/resources/keystatic-with-astro-s-content-collections.yaml, docs/src/content/resources/meet-keystatic-by-jed-watson.yaml, docs/src/content/resources/real-time-previews-with-next-js-draft-mode.yaml, docs/src/content/resources/using-keystatic-as-a-cms.yaml
https://github.com/Thinkmill/keystatic/assets/485747/4db36517-0ddf-4b7b-ab74-54e5a4d4027d
=> Resources page

packages/keystatic/src/form/fields/markdoc/editor/attributes/new-attribute.tsx, packages/keystatic/src/form/fields/markdoc/editor/autocomplete/insert-menu.tsx
Not including a changeset since it's a small thing and there are other changesets mentioning editor improvements
=> Clear autocomplete content on escape in ProseMirror editor

packages/keystatic/src/form/fields/markdoc/editor/autocomplete/EditorListbox.tsx
Not including a changeset since it's a small thing and there are other changesets mentioning editor improvements.
=> Default "empty state" for editor autocomplete

.changeset/bright-pumas-act.md, .changeset/fuzzy-spoons-attend.md, design-system/pkg/src/field/types.tsx, packages/keystatic/src/form/fields/document/ui.tsx, packages/keystatic/src/form/fields/markdoc/editor/index.tsx, packages/keystatic/src/form/fields/markdoc/ui.tsx
**@keystar/ui**
- Support "labelElementType" on `Field` component.
**@keystatic/core**
- Minor a11y fixes/improvements for document + markdoc editors.
=> Editor a11y fixes

.changeset/loud-onions-smash.md, packages/keystatic/src/form/fields/document/markdoc/markdoc.test.tsx, packages/keystatic/src/form/fields/document/markdoc/to-markdoc.tsx
Fixes #814
This fix isn't ideal since we could avoid extra wrapping but it fixes the problem of removing spaces
=> Fix marks with leading and trailing spaces

.changeset/kind-snakes-invent.md, design-system/pkg/src/table/TableView.tsx
Hi there! First of all, thank you so much for the amazing work you've been doing with Keystatic!
Recently I've noticed some browser console errors whenever landing on a collection page inside of Keystatic's Admin UI:
Turns out, DOM props were being passed to an element inside of the `TableVirtualizer` component, when they should've been filtered out. This pull request fixes that.
=> Filter out DOM props TableVirtualizer

docs/src/content/pages/fields/datetime.mdoc
Make the URL of the type signature in the [Datetime doc](https://keystatic.com/docs/fields/datetime) link to the actual page
=> Add link to the type signature page in Datetime API doc

.changeset/clever-wolves-taste.md, packages/keystatic/package.json, packages/keystatic/src/form/fields/markdoc/editor/mdx/parse.ts, packages/keystatic/src/form/fields/markdoc/editor/tests/mdx.test.tsx, pnpm-lock.yaml
Fixes #923
Note this doesn't preserve the references & definitions because that would be impractical, this just supports parsing them and serialising them inline
=> Support parsing link/image references in the mdx field

.changeset/six-spies-shout.md, docs/src/content/blog/the-fresh-keystatic-cli.mdoc, packages/keystatic/src/app/required-files.ts, packages/keystatic/src/form/api.tsx, packages/keystatic/src/form/fields/date/index.tsx, packages/keystatic/src/form/fields/datetime/index.tsx, packages/keystatic/src/form/parse-props.ts
Closes #821
Note this doesn't change the type in the reader API, that is still a string.
=> Output dates in YAML

.changeset/serious-tables-run.md, packages/keystatic/src/form/fields/markdoc/editor/mdx/serialize.ts, packages/keystatic/src/form/fields/markdoc/editor/tests/markdoc.test.tsx, packages/keystatic/src/form/fields/markdoc/editor/tests/mdx.test.tsx
=> Fix `inline` component serialisation in `fields.mdx`

docs/src/content/pages/reader-api.mdoc
Fixes #1038 - PR proposition fix for the docs' typo error.
=> fix: :memo: fix docs typo

packages/keystatic/src/app/provider.tsx
We should simply add that tag in the `<head>`: `<meta name="viewport" content="width=device-width, initial-scale=1" />`.
Sorry, I don't find how to add it in the head tag, but that solution is way better that nothing and it give the same result and make mobile way more usable.
=> Make Keystatic scale to mobile screen as it should be

.changeset/neat-insects-shop.md, packages/keystatic/package.json, packages/keystatic/src/form/fields/array/ui.tsx, packages/keystatic/src/form/fields/blocks/ui.tsx, packages/keystatic/src/form/fields/url/ui.tsx, pnpm-lock.yaml
Resolves #982
UX and A11Y improvements for `fields.array()` and `fields.blocks()` interfaces:
- Include the "required" indicator when min length validation provided by consumer.
- Connect the validation message to the group accessibly.
Unrelated:
- Minor improvement for `fields.url()` mobile soft-keyboard experience.
=> Array field required indicator

.changeset/chilled-adults-arrive.md, packages/keystatic/src/form/fields/markdoc/editor/placeholder.ts
Fixes #993 — Firefox bug where the cursor is hidden when beside a `contenteditable=false` element.
=> Editor placeholder cursor visibility

.changeset/chilly-trainers-prove.md, design-system/pkg/src/style/context.tsx
State initialisation used to assume SSR. Now CSR is optimised, conditionally. This helps with things like the initial open state of the sidebar, which would unnecessarily animate in on desktop and above.
=> Refactor breakpoint matching

.changeset/six-dodos-rescue.md, packages/keystatic/src/app/ItemPage.tsx, packages/keystatic/src/app/create-item.tsx, packages/keystatic/src/app/shell/Breadcrumbs.tsx
Abstract `HeaderBreadcrumbs` component that expects memoized `items` and `onAction` props. Memo'd breadcrumbs avoids unexpected behaviour where items collapse into a menu prematurely.
=> Fix breadcrumb collapse

.changeset/pretty-balloons-taste.md, packages/keystatic/src/form/fields/datetime/index.tsx
=> Fix `fields.datetime({ defaultValue: { kind: 'now' } })`

.changeset/silly-jobs-press.md, docs/keystatic.config.tsx, docs/src/components/navigation/badges.tsx, docs/src/components/navigation/header-nav.tsx, docs/src/components/navigation/nav-item.tsx, docs/src/content/navigation.yaml, docs/src/content/pages/fields/document.mdoc, packages/keystatic/src/form/fields/document/index.tsx
We don't have any plans to remove `fields.document` at the moment but this makes it clear that `fields.markdoc` and `fields.mdx` are the fields we recommend using for rich text.
=> Deprecate `fields.document`

.changeset/tidy-ravens-taste.md, packages/keystatic/src/form/fields/document/DocumentEditor/image.tsx, packages/keystatic/src/form/fields/file/ui.tsx, packages/keystatic/src/form/fields/image/ui.tsx, packages/keystatic/src/form/fields/markdoc/editor/schema.tsx
Fixes #974 
This was broken because we weren't passing a content type when creating the blob used as the image src (it worked for other images types since they have magic bytes that browsers will detect unlike SVGs that are just text)
=> Fix previewing SVGs in `fields.image` and the editors

packages/keystatic/src/app/CollectionPage.tsx, packages/keystatic/src/app/router.tsx, packages/keystatic/src/app/shell/sidebar/index.tsx
This PR stores the search query in the URL as a `search` query string, and it pre-populates the initial value of the collection page with the current search query.
First contribution here, so please forgive any formatting or code pattern violations 😄
=> Store search query state in URL

.changeset/new-ants-relax.md, .changeset/tough-garlics-cheer.md, dev-projects/next-app/keystatic.config.tsx, packages/keystatic/src/form/fields/markdoc/editor/custom-components.tsx, packages/keystatic/src/form/fields/markdoc/editor/popovers/index.tsx, packages/keystatic/src/form/fields/markdoc/editor/tests/mdx.test.tsx
=> Fix props of mark components not being saved and the name of inline components not being shown in `fields.markdoc` and `fields.mdx`

.changeset/four-masks-tap.md, packages/keystatic/src/form/fields/markdoc/editor/placeholder.ts
Reverts Thinkmill/keystatic#1063
This seems to have broken typing when the placeholder is visible which is much worse than the cursor sometimes not being visible.
=> Revert "Editor placeholder cursor visibility"

docs/src/content/navigation.yaml, docs/src/content/pages/recipes/nextjs-disable-admin-ui-in-production.mdoc
Hello everyone 👋
I was integrating keystatic into a Next.js project and noticed there was only a recipe for disabling admin UI in production for Astro.
I updated the docs to show how to disable (404) `keystatic` routes in production with Next.js. Hoping someone will find it helpful 🙏.
=> Docs: Added Next.js recipe for disabling admin in production

.changeset/mighty-plants-matter.md, packages/keystatic/src/app/updating.tsx, packages/keystatic/src/base64.ts
=> Fix incorrectly passing base64url encoded content to GitHub's API instead of standard base64

.changeset/lovely-vans-breathe.md, packages/keystatic/src/app/l10n/fr-FR/singletons/index.json
Hello !
How funny it was to discover the french translation for Singletons : **[Célibataires](https://www.larousse.fr/dictionnaires/francais/c%C3%A9libataire/14011#:~:text=mari%C3%A9-,c%C3%A9libataire%20n.,qui%20vit%20dans%20le%20c%C3%A9libat.)** 
It means "being single".
So I fixed it by updating the translation back to Singletons, which is valid in french [see in the dic](https://www.larousse.fr/dictionnaires/francais/singleton/72859#:~:text=Ensemble%20ne%20comprenant%20qu'un%20seul%20%C3%A9l%C3%A9ment.)
=> Update the french Singletons translation

.changeset/fuzzy-bulldogs-add.md, packages/keystatic/src/form/fields/markdoc/editor/markdoc/serialize.ts, packages/keystatic/src/form/fields/markdoc/editor/tests/markdoc.test.tsx, packages/keystatic/src/form/fields/markdoc/editor/tests/mdx.test.tsx
=> Fix whitespace on the ends of italics/bold/strikethrough breaking `fields.markdoc`

.changeset/odd-queens-smoke.md, packages/keystatic/src/form/fields/markdoc/editor/markdoc/parse.ts, packages/keystatic/src/form/fields/markdoc/editor/tests/markdoc.test.tsx, packages/keystatic/src/form/fields/markdoc/editor/tests/mdx.test.tsx
=> Fix inline components in list items being parsed into their own paragraphs in `fields.markdoc`

.changeset/popular-ladybugs-doubt.md, packages/keystatic/src/form/fields/markdoc/editor/mdx/serialize.ts, packages/keystatic/src/form/fields/markdoc/editor/tests/mdx.test.tsx
=> Fix lists in `fields.mdx` always being output as loose lists

.changeset/sweet-ducks-refuse.md, package.json, packages/keystatic/src/app/updating.tsx
Fixes #503 
Fixes #939
This error means that the GitHub App doesn't have write permissions to the configured repo. For public repos, people won't hit the "Repo not found" prompt to install the GitHub App since the repo can still be accessed without the GitHub App being installed in it. Note when using the flow to create a GitHub App, it will redirect them to install the GitHub App in the repo, this is for cases when someone is using a GitHub App created earlier or etc.
=> Suggest checking that the GitHub App is installed in the repository when committing returns a `Resource not accessible by integration` error

.changeset/polite-papayas-taste.md, packages/keystatic/src/form/fields/markdoc/editor/react-node-views.tsx
=> Fix content components UI not showing in `fields.markdoc`/`fields.mdx` until focused

.changeset/healthy-pets-act.md, packages/keystatic/src/form/fields/slug/index.tsx
The `pattern` was introduce in https://github.com/Thinkmill/keystatic/pull/1228.
However it is a required field for `slug`s. See also https://github.com/Thinkmill/keystatic/commit/36ea216c4a473eeab60aff41cb9dfabfb45127b8#r144629665
The way I read the code is, that the code actually expect the pattern to be optional by using `?.` and setting a default of `undefined`. The pattern on the `text` field is optional.
I am assuming the optionality was missing for the slug field. This PR adds it.
=> fields/slug: Make `pattern` optional for fields slug

docs/src/content/pages/reader-api.mdoc
This PR fixes a typo in the documentation related to the GitHub reader.
=> Update reader-api.mdoc to fix typo

docs/keystatic.config.tsx, docs/src/content/pages/test.mdoc
This mini PR: 
- adds an icon and description for the `tags` content component
- uses the Keystar UI `<Flex>` and `<Badge />` components instead of "arbitrary" styles
=> Add Tag icon + Keystar Badge for the tags content component

.changeset/honest-seahorses-whisper.md, packages/keystatic/src/form/fields/markdoc/editor/inputrules/rules.ts, packages/keystatic/src/form/fields/markdoc/editor/markdoc/parse.ts, packages/keystatic/src/form/fields/markdoc/editor/markdoc/serialize.ts, packages/keystatic/src/form/fields/markdoc/editor/mdx/parse.ts, packages/keystatic/src/form/fields/markdoc/editor/mdx/serialize.ts, packages/keystatic/src/form/fields/markdoc/editor/schema.tsx, packages/keystatic/src/form/fields/markdoc/editor/tests/lists.test.tsx, packages/keystatic/src/form/fields/markdoc/editor/tests/markdoc.test.tsx, packages/keystatic/src/form/fields/markdoc/editor/tests/mdx.test.tsx, packages/keystatic/src/form/fields/markdoc/editor/tests/pasting/from-other-editors.test.tsx, packages/keystatic/src/form/fields/markdoc/editor/tests/pasting/markdown.test.tsx
=> Support ordered lists that don't start at 1 in `fields.markdoc` and `fields.mdx`

.changeset/proud-buckets-kick.md, design-system/pkg/src/tag/docs/index.mdoc
Handy, since I need to bump [package versioning](https://github.com/Thinkmill/keystatic/pull/1277). It got stuck on:
> Expected — Waiting for status to be reported
=> Fix tag docs typo

docs/src/app/mailing-list/route.ts
Updates the `tag` applied when adding a subscriber to the Thinkmill newsletter. This PR formats the tag consistently with the Keystone and Thinkmill websites.
=> Fix: Update to Newsletter Subscription Tag

.changeset/swift-emus-film.md, packages/keystatic/src/app/CollectionPage.tsx
=> Show columns of other entries on the collection page when some entries fail to parse

.changeset/gorgeous-cats-wave.md, .changeset/khaki-elephants-cry.md, design-system/pkg/src/menu/Menu.tsx, design-system/pkg/src/menu/MenuItem.tsx, design-system/pkg/src/menu/MenuSection.tsx, design-system/pkg/src/menu/test/Menu.test.tsx
This was mainly visible in the menu in tables in the editor where adding/removing rows/columns and when inserting custom components. This mirrors the changes in https://github.com/adobe/react-spectrum/pull/6671
=> Fix `<Menu>` `onAction` being double called

.changeset/hip-trees-swim.md, packages/astro/src/api.tsx
=> Support `@astrojs/cloudflare@10.0.0` and above

.changeset/strong-snakes-repair.md, design-system/pkg/src/calendar/CalendarCell.tsx, design-system/pkg/src/core/cssCustomProperties.ts, design-system/pkg/src/date-time/DateField.tsx, design-system/pkg/src/date-time/DatePicker.tsx, design-system/pkg/src/date-time/Input.tsx, design-system/pkg/src/menu/types.ts, design-system/pkg/src/number-field/NumberField.tsx, design-system/pkg/src/tag/TagGroup.tsx
Address quirks and bugs encountered while implementing Keystone admin UI.
=> Misc. component lib fixes and improvements

docs/src/content/pages/fields/markdoc.mdoc, docs/src/content/pages/fields/mdx.mdoc
I consider this a quick fix to at least hint at the options by linking to the respective type signature files. The old [document docs](https://keystatic.com/docs/fields/document) had longer sections on those customization topics. It might be worth expanding on this in the future, similar to what the Document field docs had. But for now those sections would have helped me find what I was looking for…
=> Docs mdx: Add sections on custom `options`

.changeset/mighty-apples-tan.md, packages/keystatic/src/form/fields/markdoc/editor/code-block-highlighting.ts
Closes #1353
This doesn't add an option for this since this behavior is just more correct imo. e.g. while the CommonMark spec talks about how the meaning of the info string isn't strictly defined, it [mentions that specifically the first word is typically used, not the whole info string](https://spec.commonmark.org/0.31.2/#:~:text=the%20first%20word%20is%20typically%20used%20to%20specify%20the%20language)
=> Use first word only from info string to match language in code block highlighting

.changeset/spotty-badgers-punch.md, packages/keystatic/src/api/api-node.ts
In the spirit of https://github.com/Thinkmill/keystatic/pull/1359, I wonder if the `.env` file should just have the link to the app on GitHub right there.
This would make the docs more or less obsolete for users who know how to find the app settings once they have their apps page.
--- 
Disclaimer: I did not run this code (due to https://github.com/Thinkmill/keystatic/discussions/1285).
=> Link to github app in `.env` for `slugEnv`

.changeset/seven-mugs-retire.md, design-system/pkg/src/field/FieldDescription.tsx, design-system/pkg/src/field/FieldPrimitive.tsx, design-system/pkg/src/field/index.ts, packages/keystatic/src/form/fields/array/ui.tsx, packages/keystatic/src/form/fields/blocks/ui.tsx, packages/keystatic/src/form/fields/file/ui.tsx, packages/keystatic/src/form/fields/image/ui.tsx
Expose `FieldDescription` from "@keystar/ui/field" package.
=> UI field description

.changeset/sour-ravens-know.md, packages/keystatic/src/api/generic.ts
Fixes #1357
Note this only fixes the issue described in the title of #1357, the other problem described in the issue where there's a blank page in GitHub App creation flow seems to be something with Astro refreshing after Keystatic writes the env variables which I'm hoping to look into more
=> Return more useful error when reaching `/api/keystatic/github/created-app` route when the GitHub App is already setup

.changeset/fast-trainers-watch.md, packages/keystatic/src/app/memoize.ts, packages/keystatic/src/app/path-utils.ts
=> Improve error for invalid content field

.changeset/nice-parrots-sort.md, packages/keystatic/src/app/onboarding/setup.tsx
Before, it was possible to provide `https://foo.com/` as input and generate a redirect_uri like `https://foo.com//api/keystatic/github/oauth/callback` which triggers the "The `redirect_uri` is not associated with this application." error by Github. Now the path is merged with the URL correctly for any valid URL input.
---
Disclaimer: This is untested, because of https://github.com/Thinkmill/keystatic/discussions/1285 but I think it should be fine.
=> Onboarding: Guard deployedURL

.changeset/modern-ghosts-fly.md, packages/keystatic/src/app/l10n/pl-PL/add/index.json, packages/keystatic/src/app/l10n/pl-PL/cancel/index.json, packages/keystatic/src/app/l10n/pl-PL/create/index.json, packages/keystatic/src/app/l10n/pl-PL/currentBranch/index.json, packages/keystatic/src/app/l10n/pl-PL/defaultBranch/index.json, packages/keystatic/src/app/l10n/pl-PL/delete/index.json, packages/keystatic/src/app/l10n/pl-PL/deleteBranch/index.json, packages/keystatic/src/app/l10n/pl-PL/edit/index.json, packages/keystatic/src/app/l10n/pl-PL/save/index.json, packages/keystatic/src/app/l10n/pl-PL/singleton/index.json
I fixed errors in Polish translations, including changing ‘Dodać’ to ‘Dodaj’, and corrected several other inaccuracies.
=> Fix polish translations

.changeset/good-files-teach.md, design-system/pkg/src/action-bar/ActionBar.tsx
I was working with extending the Keystone custom pages for List view with custom actions.
Seems like `ActionGroup` always collapsed and does not allow me adding visible buttons in the `ActionBar`.
this fixes the behavior which allows me use `Actionbar` with multiple items in the `ActionGroup` shown with the same key `buttonLabelBehavior`
default value is `collapse` for `ActionBar` anyways
before:
after:
=> Fix ActionGroup always collapsed button label

.changeset/strong-bikes-cheer.md, design-system/pkg/src/toast/Toast.tsx
Implements better handling of "neutral" toast appearance, especially for dark mode.
| Before | After |
|--------|--------|
| <img width="210" height="72" alt="washed-out toast screenshot" src="https://github.com/user-attachments/assets/7f1a1a9c-ec5f-45a6-b680-71cf5f45bde9" /> | <img width="210" height="72" alt="good contrast screenshot" src="https://github.com/user-attachments/assets/ac16e5ec-3857-4f39-9de5-bc211ca9241d" /> |
=> Improve `Toast` appearance of "neutral" variant
