- .changeset/tidy-yaks-fix.md
- design-system/packages/button/src/useActionButtonStyles.tsx
- design-system/packages/dialog/src/Dialog.tsx
- design-system/packages/dialog/src/index.ts
- design-system/packages/dialog/src/useDialogContainer.ts
- design-system/packages/dialog/stories/AlertDialog.stories.tsx
- design-system/packages/dialog/stories/Dialog.stories.tsx
- design-system/packages/dialog/stories/DialogContainer.stories.tsx
- design-system/packages/dialog/stories/DialogTrigger.stories.tsx
Export `useDialogContainer` from "@voussoir/dialog". A dialog may be abstracted from its trigger; this hook provides access to context.
> Dialog container hook

- .changeset/modern-feet-thank.md
- keystatic/DocumentEditor/Toolbar.tsx
Use `Picker` for the heading menu.
> Document editor toolbar heading menu

- keystatic/README.md
Just something simple so it's more obvious what this directory is for, and how to get it running
(secrets are actually secret, I believe, but we can add instructions later on how to get it running without them)
> Adding readme for the keystatic dev app

- .changeset/beige-suits-hide.md
- .changeset/kind-geckos-warn.md
- .changeset/three-sheep-camp.md
- design-system/docs/package.json
- keystatic/local-config.tsx
- packages/keystatic/DocumentEditor/component-blocks/api.tsx
- packages/keystatic/DocumentEditor/component-blocks/chromeful-element.tsx
- packages/keystatic/DocumentEditor/component-blocks/form-from-preview.tsx
- packages/keystatic/DocumentEditor/component-blocks/preview-props.tsx
- packages/keystatic/DocumentEditor/component-blocks/utils.ts
- packages/keystatic/app/ItemPage.tsx
- packages/keystatic/app/SingletonPage.tsx
- packages/keystatic/app/create-item.tsx
- packages/keystatic/app/useHasChanged.ts
- packages/keystatic/app/useItemData.ts
- packages/keystatic/app/useSlugsInCollection.ts
- packages/keystatic/app/utils.ts
- packages/keystatic/config.tsx
- packages/keystatic/markdoc/find-children.test.ts
- packages/keystatic/package.json
- packages/keystatic/reader.test.tsx
- packages/keystatic/src/reader.ts
- packages/keystatic/test-data/posts/2023-is-finally-here/index.yaml
- packages/keystatic/utils.tsx
- packages/keystatic/validate-component-block-props.ts
- packages/keystatic/validation.ts
- pnpm-lock.yaml
> Slug improvements

- README.md
- keystatic/local-config.tsx
- keystatic/package.json
- keystatic/pages/global.css
- keystatic/pages/index.tsx
- packages/keystatic/DocumentEditor/component-blocks/api.tsx
- packages/keystatic/DocumentEditor/component-blocks/chromeful-element.tsx
- packages/keystatic/DocumentEditor/component-blocks/form-from-preview.tsx
- pnpm-lock.yaml
Adjust how images are presented in component blocks; add some chrome and use `max{Height|Width}` to maintain aspect ratio.
> Image presentation

- .changeset/long-sheep-attack.md
- design-system/packages/combobox/src/MobileCombobox.tsx
- packages/keystatic/DocumentEditor/code-block.tsx
- packages/keystatic/DocumentEditor/index.tsx
- packages/keystatic/DocumentEditor/leaf.tsx
- prism leaf: use theme colours (dark-mode support)
- code-block: move language selection inline
> Code block; syntax highlighting

- .changeset/thin-lemons-grin.md
- packages/keystatic/DocumentEditor/component-blocks/api.tsx
- packages/keystatic/DocumentEditor/component-blocks/fields/array.tsx
- packages/keystatic/DocumentEditor/component-blocks/fields/slug.tsx
- packages/keystatic/DocumentEditor/component-blocks/fields/text.tsx
- packages/keystatic/DocumentEditor/component-blocks/form-from-preview.tsx
- packages/keystatic/DocumentEditor/component-blocks/utils.ts
- packages/keystatic/app/ItemPage.tsx
- packages/keystatic/app/create-item.tsx
- packages/keystatic/app/required-files.ts
- packages/keystatic/app/useItemData.ts
- packages/keystatic/markdoc/find-children.test.ts
- packages/keystatic/markdoc/to-markdoc.tsx
- packages/keystatic/src/reader.ts
- packages/keystatic/utils.tsx
- packages/keystatic/validate-component-block-props.ts
This lets people avoid having the files within an array field be organised by index
> slugField in array fields

- .changeset/twenty-penguins-talk.md
- packages/keystatic/DocumentEditor/BlockPopoverTrigger.tsx
- packages/keystatic/DocumentEditor/component-blocks/api.tsx
- packages/keystatic/DocumentEditor/component-blocks/chromeful-element.tsx
- packages/keystatic/DocumentEditor/image.tsx
- packages/keystatic/DocumentEditor/index.tsx
- packages/keystatic/DocumentEditor/link.tsx
- packages/keystatic/DocumentEditor/utils.ts
Move image details into a modal dialog, which can be invoked from an actions popover. Align the link popover with the new style:
- popovers for simple actions
- modals for data entry and more complex interactions
> Editor dialogs

- .changeset/fix-editor-cell-navigation.md
- .changeset/fix-editor-table-styles.md
> Add missing changesets

- .changeset/cool-hounds-accept.md
- design-system/docs/pages/_app.tsx
> Docs toast fix

- .changeset/funny-dragons-lay.md
- design-system/packages/toast/src/Toaster.tsx
- packages/keystatic/app/create-item.tsx
- packages/keystatic/app/dashboard/DashboardPage.tsx
- packages/keystatic/app/provider.tsx
- packages/keystatic/package.json
- pnpm-lock.yaml
Introduce toasts to the app. Show a "positive" toast when an entry is created.
> App toasts

- .changeset/few-shrimps-destroy.md
- packages/keystatic/DocumentEditor/primitives/BlockPopover.tsx
- packages/keystatic/DocumentEditor/table.tsx
Move the editor table's "header row" toggle to a block popover.
> Editor table block popover

- .changeset/cyan-pots-sort.md
- design-system/packages/avatar/src/Avatar.tsx
- design-system/packages/menu/src/ActionMenu.tsx
- design-system/packages/menu/stories/ActionMenu.stories.tsx
- design-system/packages/toast/stories/Toast.stories.tsx
- "@voussoir/avatar": stop `Avatar` shrinking within flex container
- "@voussoir/menu": support selection on `ActionMenu` component
- "@voussoir/toast": fix imports in stories
> Misc fixes

- .changeset/neat-insects-help.md
- design-system/packages/types/src/typography.ts
- design-system/packages/typography/src/heading/useHeadingStyles.ts
- design-system/packages/typography/stories/Heading.stories.tsx
Support "align" prop on `Heading` component.
> Heading alignment

- .changeset/eighty-pandas-chew.md
- packages/keystatic/DocumentEditor/block-schema.test.tsx
- packages/keystatic/DocumentEditor/blockquote/blockquote-ui.tsx
- packages/keystatic/DocumentEditor/editor.tsx
- packages/keystatic/DocumentEditor/pasting/pasting-within-editor.test.tsx
- packages/keystatic/DocumentEditor/tests/jsx/namespace.d.ts
- packages/keystatic/app/shell/data.tsx
(moving the elements in reverse is what actually fixes it)
> Fix pasting reversing

- .changeset/pink-ears-sparkle.md
- keystatic/local-config.tsx
- packages/keystatic/DocumentEditor/Toolbar.tsx
- packages/keystatic/DocumentEditor/block-markdown-shortcuts.ts
- packages/keystatic/DocumentEditor/code-block/code-block-ui.tsx
- packages/keystatic/DocumentEditor/component-blocks/fields/document/index.tsx
- packages/keystatic/DocumentEditor/component-blocks/utils.ts
- packages/keystatic/DocumentEditor/custom-attributes.tsx
- packages/keystatic/DocumentEditor/document-features-normalization.ts
- packages/keystatic/DocumentEditor/document-features.ts
- packages/keystatic/DocumentEditor/heading/heading.tsx
- packages/keystatic/DocumentEditor/insert-menu.tsx
- packages/keystatic/DocumentEditor/primitives/BlockPopover.tsx
- packages/keystatic/DocumentEditor/toolbar-state.tsx
- packages/keystatic/markdoc/from-markdoc.ts
- packages/keystatic/markdoc/test-utils.ts
- packages/keystatic/markdoc/to-markdoc.tsx
- packages/next/src/api.tsx
This lets you add things like ids on headings or filenames on code blocks
> Abitrary attributes on headings and code blocks

- .changeset/pretty-trainers-design.md
- packages/keystatic/src/renderer.tsx
> `DocumentRenderer` fixes

- .changeset/khaki-roses-check.md
- design-system/docs/package.json
- design-system/packages/switch/README.md
- design-system/packages/switch/docs/index.md
- design-system/packages/switch/package.json
- design-system/packages/switch/src/Switch.tsx
- design-system/packages/switch/src/index.ts
- design-system/packages/switch/stories/Switch.stories.tsx
- design-system/packages/switch/test/Switch.test.tsx
- pnpm-lock.yaml
New package "@voussoir/switch" exports `Switch` component.
> Switches allow users to toggle a discrete option on or off. They are usually used to activate or deactivate a specific setting.
> Switch component

- .changeset/nervous-ravens-boil.md
- design-system/packages/core/src/ClientSideOnlyDocumentElement.tsx
- design-system/packages/core/src/VoussoirProvider.tsx
- design-system/packages/core/src/context.tsx
- design-system/packages/core/src/index.ts
Refactor to avoid hot-reload issue when in development.
> Provider context

- .changeset/nine-jobs-drive.md
- packages/keystatic/src/form/fields/conditional/ui.tsx
- packages/keystatic/src/form/fields/object/ui.tsx
Increase the gap value to `xlarge` between fields in a data entry form.
> Increase gap between fields in data entry form

- .changeset/empty-monkeys-exist.md
- design-system/packages/button/package.json
- design-system/packages/button/src/ToggleButton.tsx
- design-system/packages/button/src/index.ts
- design-system/packages/button/src/types.ts
- design-system/packages/button/src/useActionButtonStyles.tsx
- design-system/packages/button/stories/ToggleButton.stories.tsx
- pnpm-lock.yaml
New `ToggleButton` exported from "@voussoir/button" package.
> Toggle button

- docs/src/app/(public)/docs/[...slug]/page.tsx
- docs/src/components/document-renderer.tsx
- docs/src/components/navigation/social-links.tsx
- docs/src/content/navigation.yaml
- docs/src/content/pages/collections-and-singletons.mdoc
- docs/src/content/pages/frequently-asked-questions.mdoc
- docs/src/content/pages/how-keystatic-organises-your-content.mdoc
- docs/src/content/pages/installation-astro.mdoc
- docs/src/content/pages/installation-next-js.mdoc
- docs/src/content/pages/local-vs-git-hub-storage-strategy.mdoc
- docs/src/content/pages/reader-api.mdoc
- docs/src/content/pages/renderer-api.mdoc
- docs/src/styles/keystatic-theme.json
- docs/src/utils/reader.ts
- Changes as per https://linear.app/keystatic/issue/KEY-147/content-updates
- Sorted Fields API nav items to be in alphabetical order for easier wayfinding
- Custom highlight theme (based on github-light but with a Keystatic flare)
> KEY-147: Content updates

- docs/keystatic.config.tsx
- docs/src/content/pages/automated-setup-with-template.mdoc
- docs/src/content/pages/fields/relationship.mdoc
- docs/src/content/pages/how-keystatic-organises-your-content.mdoc
- docs/src/content/pages/local-vs-git-hub-storage-strategy.mdoc
- docs/src/content/pages/reader-api.mdoc
Right now, this will be a worse editor experience but it's how the Markdoc should look and will be necessary for the new editor (I want to try the new editor on the docs content to see how it is)
> Change aside component in docs site

- packages/keystatic/src/form/fields/markdoc/editor/markdoc/parse.ts
- packages/keystatic/src/form/fields/markdoc/editor/markdoc/serialize.ts
- packages/keystatic/src/form/fields/markdoc/editor/tests/markdoc.test.tsx
- packages/keystatic/src/form/fields/markdoc/editor/tests/utils.tsx
Fix parsing inline code in new editor
> Fix parsing inline code in new editor

- packages/keystatic/src/form/fields/markdoc/editor/editor-state.tsx
- packages/keystatic/src/form/fields/markdoc/editor/markdoc/parse.ts
- packages/keystatic/src/form/fields/markdoc/editor/schema.tsx
- packages/keystatic/src/form/fields/markdoc/editor/tests/code-block.test.tsx
Slightly fix some bits of code blocks in the new editor
> Slightly fix some bits of code blocks in the new editor

- .changeset/weak-owls-flow.md
- packages/next/package.json
Fix next peer dependency in @keystatic/next
> Fix next peer dependency in @keystatic/next

- packages/keystatic/src/form/fields/markdoc/editor/Toolbar.tsx
- packages/keystatic/src/form/fields/markdoc/editor/attributes/index.ts
- packages/keystatic/src/form/fields/markdoc/editor/attributes/new-attribute.tsx
- packages/keystatic/src/form/fields/markdoc/editor/attributes/schema.ts
- packages/keystatic/src/form/fields/markdoc/editor/autocomplete/insert-menu.tsx
- packages/keystatic/src/form/fields/markdoc/editor/commands/keymap.ts
- packages/keystatic/src/form/fields/markdoc/editor/gapcursor/gapcursor.ts
- packages/keystatic/src/form/fields/markdoc/editor/markdoc/parse.ts
- packages/keystatic/src/form/fields/markdoc/editor/schema.tsx
- packages/keystatic/src/form/fields/markdoc/editor/utils.ts
First pass at improved styles for tags in the new editor
> First pass at improved styles for tags in the new editor

- packages/keystatic/src/form/fields/markdoc/editor/inputrules/rules.ts
> Fix heading input rule

- packages/keystatic/package.json
- packages/keystatic/src/form/fields/markdoc/editor/attributes/index.ts
- packages/keystatic/src/form/fields/markdoc/editor/attributes/schema.ts
- packages/keystatic/src/form/fields/markdoc/editor/autocomplete/autocomplete.tsx
- packages/keystatic/src/form/fields/markdoc/editor/editor-view.tsx
- packages/keystatic/src/form/fields/markdoc/editor/index.tsx
- packages/keystatic/src/form/fields/markdoc/editor/popovers/index.tsx
- packages/keystatic/src/form/fields/markdoc/editor/popovers/reference.tsx
- packages/keystatic/src/form/fields/markdoc/editor/schema.tsx
- packages/keystatic/src/form/fields/markdoc/editor/tests/utils.tsx
- packages/keystatic/src/form/fields/markdoc/editor/utils.ts
- pnpm-lock.yaml
Fix link popover and tag/attributes pasting
> Fix link popover and tag/attributes pasting

- .changeset/red-pants-dream.md
- design-system/packages/overlays/src/Popover.tsx
Resolves #334
Refactor placement implementation to fix bug where popover fails to flip when invoked for the first time.
> Popover placement

- .changeset/violet-news-check.md
- design-system/packages/list-view/src/ListView.tsx
- packages/keystatic/src/app/shell/index.tsx
Fix unwanted scrollbars where appropriate.
> Unwanted scrollbars

- .changeset/twelve-ducks-hide.md
- design-system/pkg/src/table/styles.tsx
- keystatic/local-config.tsx
- packages/keystatic/src/app/CollectionPage.tsx
- packages/keystatic/src/app/shell/header.tsx
- packages/keystatic/src/app/shell/panels.tsx
Tidy panels and collection table appearance
> Collection page tidy

- .changeset/green-tips-wave.md
- design-system/pkg/src/action-group/index.ts
- design-system/pkg/src/avatar/index.ts
- design-system/pkg/src/badge/index.ts
- design-system/pkg/src/breadcrumbs/index.ts
- design-system/pkg/src/button/index.ts
- design-system/pkg/src/checkbox/index.ts
- design-system/pkg/src/combobox/index.ts
- design-system/pkg/src/field/index.ts
- design-system/pkg/src/icon/index.ts
- design-system/pkg/src/image/index.ts
- design-system/pkg/src/layout/index.ts
- design-system/pkg/src/link/index.ts
- design-system/pkg/src/list-view/index.ts
- design-system/pkg/src/menu/index.ts
- design-system/pkg/src/nav-list/index.ts
- design-system/pkg/src/notice/index.ts
- design-system/pkg/src/number-field/index.ts
- design-system/pkg/src/overlays/index.ts
- design-system/pkg/src/password-field/index.ts
- design-system/pkg/src/picker/index.ts
- design-system/pkg/src/progress/index.ts
- design-system/pkg/src/radio/index.ts
- design-system/pkg/src/search-field/index.ts
- design-system/pkg/src/slots/index.ts
- design-system/pkg/src/tabs/index.ts
- design-system/pkg/src/text-field/index.ts
- design-system/pkg/src/toast/index.ts
- design-system/pkg/src/tooltip/index.ts
- design-system/pkg/src/typography/index.ts
Add 'use client' pragma to exports, where missing.
> Use client pragma

- .changeset/afraid-lobsters-flow.md
- packages/keystatic/src/form/fields/document/DocumentEditor/component-blocks/document-field.tsx
- packages/keystatic/src/form/fields/file/index.tsx
- packages/keystatic/src/form/fields/image/getSrcPrefix.tsx
- packages/keystatic/src/form/fields/image/index.tsx
Fixes #471
Related: https://github.com/Thinkmill/keystatic/discussions/372
> Stop automatically adding leading `/` to `publicPath`

- docs/src/app/(public)/page.tsx
- docs/src/components/intro.tsx
- docs/src/components/storytelling.tsx
> Replace templates with start of storytelling — for now just a video

- design-system/pkg/src/split-view/docs/index.md
> Split view docs

- .changeset/early-paws-shout.md
- design-system/pkg/package.json
- design-system/pkg/src/badge/Badge.tsx
- design-system/pkg/src/button/Button.tsx
- design-system/pkg/src/button/useButtonStyles.tsx
- design-system/pkg/src/layout/Stack.tsx
- design-system/pkg/src/layout/index.ts
- design-system/pkg/src/overlays/Tray.tsx
- design-system/pkg/src/status-light/StatusLight.tsx
- design-system/pkg/src/status-light/docs/index.md
- design-system/pkg/src/status-light/index.ts
- design-system/pkg/src/status-light/stories/StatusLight.stories.tsx
- design-system/pkg/src/status-light/test/StatusLight.tsx
- design-system/pkg/status-light/package.json
A few updates and additions for work on the cloud app
> Cloud UI requirements

- .changeset/swift-penguins-reflect.md
- design-system/pkg/src/toast/ToastContainer.tsx
- design-system/pkg/src/toast/stories/Toast.stories.tsx
- design-system/pkg/src/toast/types.ts
Support "position" and "placement" props on `Toaster`, and fix RTL implementation.
> Toaster position

- docs/src/components/document-renderer.tsx
- docs/src/components/navigation/nav-item.tsx
> KEY-184: Increase badges contrast for a11y

- .changeset/moody-jokes-breathe.md
- design-system/pkg/src/table/styles.tsx
- packages/keystatic/src/app/CollectionPage.tsx
- packages/keystatic/src/app/dashboard/components.tsx
- packages/keystatic/src/app/provider.tsx
- packages/keystatic/src/app/shell/page.tsx
App:
- collection: on mobile, toggle the search field visibility
- collection: low prominence table
- dashboard: fix card focus appearance
- page header always full-width
- switch app background to "canvas"
Component library:
- fix table column sort cursor
> Frontend changes

- .changeset/quick-cows-attend.md
- packages/keystatic/src/app/ui.tsx
> KEY-225 Fix GitHub login button leading to a 404 with `@keystatic/astro`

- docs/src/content/pages/fields/image.mdoc
> Update image.mdoc for a spelling mistake

- .changeset/tall-peas-design.md
- packages/keystatic/src/app/CollectionPage.tsx
- packages/keystatic/src/app/ItemPage.tsx
- packages/keystatic/src/app/create-item.tsx
- packages/keystatic/src/app/dashboard/BranchSection.tsx
- packages/keystatic/src/app/dashboard/CollectionSection.tsx
- packages/keystatic/src/app/dashboard/DashboardPage.tsx
- packages/keystatic/src/app/dashboard/SingletonSection.tsx
- packages/keystatic/src/app/dashboard/components.tsx
- packages/keystatic/src/app/shell/common.tsx
- packages/keystatic/src/app/shell/context.tsx
- packages/keystatic/src/app/shell/index.tsx
- packages/keystatic/src/app/shell/page.tsx
- packages/keystatic/src/app/shell/topbar.tsx
[KEY-229](https://linear.app/keystatic/issue/KEY-229/ui-polishes-and-refinements)
> Misc. UI changes—align with Figma designs

- .changeset/witty-bats-listen.md
- design-system/pkg/src/breadcrumbs/BreadcrumbItem.tsx
- design-system/pkg/src/date-time/InputSegment.tsx
- design-system/pkg/src/field/Field.tsx
- design-system/pkg/src/field/FieldPrimitive.tsx
- design-system/pkg/src/field/types.tsx
- design-system/pkg/src/text-field/TextFieldPrimitive.tsx
- design-system/pkg/src/typography/Prose.tsx
- design-system/pkg/src/typography/index.ts
- design-system/pkg/src/typography/stories/Prose.stories.tsx
- design-system/pkg/src/typography/text/useTextStyles.ts
- dev-projects/next-app/keystatic.config.tsx
- packages/keystatic/src/app/entry-form.tsx
- packages/keystatic/src/form/fields/document/DocumentEditor/Toolbar.tsx
- packages/keystatic/src/form/fields/document/DocumentEditor/blockquote/blockquote-ui.tsx
- packages/keystatic/src/form/fields/document/DocumentEditor/code-block/code-block-ui.tsx
- packages/keystatic/src/form/fields/document/DocumentEditor/divider.tsx
- packages/keystatic/src/form/fields/document/DocumentEditor/heading/heading.tsx
- packages/keystatic/src/form/fields/document/DocumentEditor/index.tsx
- packages/keystatic/src/form/fields/document/DocumentEditor/leaf.tsx
- packages/keystatic/src/form/fields/document/DocumentEditor/render-element.tsx
- packages/keystatic/src/form/fields/document/ui.tsx
Optimise the editor appearance when `entryLayout="content"` for a more focused experience.
Component library:
- Update the antialiasing behaviour everywhere 
- New `Prose` component from "@keystar/ui/typography" package.
- Improve `Field` implementation and types
> Document editor main content

- docs/src/content/navigation.yaml
> Add Discord link in the nav's "Community" section

- .changeset/stupid-mayflies-collect.md
- design-system/pkg/src/text-field/TextFieldPrimitive.tsx
Increase line-height on `TextArea` component.
> Textarea lineheight

- .changeset/odd-cycles-heal.md
- packages/keystatic/src/app/shell/context.tsx
- packages/keystatic/src/app/shell/page.tsx
- packages/keystatic/src/app/shell/panels.tsx
Resolves #557 
Move content panel resize observer higher in the tree to avoid issues.
> Content panel container queries

- .changeset/tasty-jokes-live.md
- design-system/pkg/src/split-view/SplitView.tsx
- design-system/pkg/src/split-view/types.ts
- design-system/pkg/src/utils/index.ts
- design-system/pkg/src/utils/useIsMounted.ts
Prevent undesirable panel animation during mount
> Split view animation

- packages/keystatic/src/component-blocks/cloud-image-preview.tsx
This reverts commit 83a02e3a7c0b1a2fc25784b8e72db4951ecd24c1.
> Revert "Fix Firefox bug cleaning up cloud image components (#568)"

- docs/src/content/pages/installation-next-js.mdoc
Brings the Next.js intro inline with the Astro page.
Fun fact: I used Keystatic (running in local mode) **entirely** to make this change 😁
> Update Next.js setup guide

- packages/keystatic/src/component-blocks/cloud-image-preview.tsx
Quick fix now that #565 has landed
> Add image component edit tooltip

- design-system/pkg/src/typography/Prose.tsx
- packages/keystatic/src/form/fields/document/DocumentEditor/index.tsx
- packages/keystatic/src/form/fields/document/DocumentEditor/ui-utils.ts
Adjust spacing and typography for the document editor.
> Prose tweaks

- .changeset/afraid-garlics-poke.md
- packages/keystatic/src/component-blocks/cloud-image-preview.tsx
- packages/keystatic/src/form/fields/cloudImage/index.tsx
- packages/keystatic/src/form/fields/cloudImage/ui.tsx
- packages/keystatic/src/form/fields/index.ts
I think we'll want to iterate on some stuff around validation but this should be an okay start
> Cloud image field

- packages/keystatic/src/component-blocks/cloud-image-preview.tsx
Just the actual bug fix from #591. No changeset since this bug hasn't been released.
> Fix cloud image block editing

- .changeset/serious-crabs-mate.md
- design-system/pkg/src/layout/Divider.tsx
Fix "vertical" `Divider` styles.
> Divider styles

- templates/astro/src/content/config.ts
Adding a sample config file for Astro template so it is created automatically when people use Keystatic cli to starting a new project.
> Astro config.ts in the template

- .changeset/little-donuts-cross.md
- docs/src/content/pages/installation-astro.mdoc
- packages/create/src/actions/outro.ts
- templates/astro/README.md
Updated Astro related docs with some extra steps and fixed the port number.
> Astro docs

- .changeset/moody-buttons-grow.md
- packages/keystatic/src/form/api.tsx
- packages/keystatic/src/form/fields/document/DocumentEditor/component-blocks/chromeful-element.tsx
Editing of the fields should happen in a modal instead of in-document.
> Fields editing: modal

- .changeset/light-oranges-stare.md
- dev-projects/next-app/package.json
- packages/keystatic/package.json
- packages/keystatic/src/app/ItemPage.tsx
- packages/keystatic/src/app/SingletonPage.tsx
- packages/keystatic/src/app/persistence.tsx
- packages/keystatic/src/app/updating.tsx
- packages/keystatic/src/app/useHasChanged.ts
- packages/keystatic/src/app/useItemData.ts
- pnpm-lock.yaml
> Persist draft changes to entries to browser storage

- babel.config.json
- design-system/docs/package.json
- dev-projects/localization/.eslintrc.json
- package.json
- packages/keystatic/jest-setup.ts
- pnpm-lock.yaml
https://github.com/tc39/proposal-explicit-resource-management, I want to use this in tests, it's already supported in TypeScript
> Allow using explicit resource management proposal in tests

- .changeset/chilled-coins-search.md
- packages/keystatic/src/form/fields/document/index.tsx
> Fix invalid directory in content field serialization error

- .changeset/twelve-suits-hide.md
- design-system/pkg/src/table/TableView.tsx
- design-system/pkg/src/table/stories/Table.stories.tsx
- design-system/pkg/src/table/styles.tsx
- packages/keystatic/src/app/CollectionPage.tsx
See commits. Added lines are mostly stories.
App change: support `mod+f` on collection page.
> Table view cleanup

- packages/keystatic/src/form/fields/document/DocumentEditor/Toolbar.tsx
No changeset since the change that this code came from hasn't been released yet
> Fix missing key

- .changeset/dirty-paws-glow.md
- design-system/docs/package.json
- design-system/pkg/package.json
- dev-projects/localization/package.json
- dev-projects/next-app/package.json
- dev-projects/next-blocks-builder/package.json
- docs/package.json
- docs/src/app/og/route.tsx
- packages/next/package.json
- pnpm-lock.yaml
- templates/nextjs/package.json
> Allow next@14 in peerDependencies and use next@14 locally

- docs/src/content/navigation.yaml
- docs/src/content/pages/cloud.mdoc
@JedWatson — you probably want to update the copy on this, but I think it's a good "placeholder" or reveal 👍
> New Keystatic Cloud page

- .changeset/perfect-trains-refuse.md
- packages/keystatic/jest.config.js
- packages/keystatic/src/form/fields/document/markdoc/from-markdoc.ts
- packages/keystatic/src/form/fields/document/markdoc/markdoc.test.tsx
- packages/keystatic/src/form/fields/document/markdoc/to-markdoc.tsx
> Fix links and other formatting around inline code being discarded in the document editor

- .changeset/smooth-waves-itch.md
- design-system/docs/components/example-helpers.tsx
- design-system/docs/components/mdx-components/client-markdoc-components.tsx
- design-system/pkg/src/action-group/ActionGroup.tsx
- design-system/pkg/src/action-group/stories/ActionGroup.stories.tsx
- design-system/pkg/src/breadcrumbs/BreadcrumbItem.tsx
- design-system/pkg/src/breadcrumbs/Breadcrumbs.tsx
- design-system/pkg/src/button/ActionButton.tsx
- design-system/pkg/src/button/Button.tsx
- design-system/pkg/src/button/useActionButtonStyles.tsx
- design-system/pkg/src/button/useButtonStyles.tsx
- design-system/pkg/src/checkbox/Checkbox.tsx
- design-system/pkg/src/combobox/Combobox.tsx
- design-system/pkg/src/combobox/MobileCombobox.tsx
- design-system/pkg/src/combobox/class-list.ts
- design-system/pkg/src/combobox/index.ts
- design-system/pkg/src/date-time/InputSegment.tsx
- design-system/pkg/src/dialog/Dialog.tsx
- design-system/pkg/src/layout/Divider.tsx
- design-system/pkg/src/menu/Menu.tsx
- design-system/pkg/src/menu/MenuSection.tsx
- design-system/pkg/src/notice/Notice.tsx
- design-system/pkg/src/password-field/PasswordField.tsx
- design-system/pkg/src/radio/Radio.tsx
- design-system/pkg/src/style/classNames.ts
- design-system/pkg/src/typography/heading/useHeadingStyles.ts
- design-system/pkg/src/typography/text/useTextStyles.ts
- packages/keystatic/src/app/branch-selection.tsx
Support link as `ActionGroup` items.
> Action group links

- packages/keystatic/src/app/ItemPage.tsx
- packages/keystatic/src/app/SingletonPage.tsx
No changeset since the one from #721 already describes it
> Convert more buttons to links in the app

- .changeset/wicked-pens-tease.md
- packages/keystatic/src/app/shell/common.tsx
- packages/keystatic/src/app/shell/sidebar.tsx
- packages/keystatic/src/app/shell/topbar.tsx
- packages/keystatic/src/config.tsx
New config `ui` supports branding options.
> Interface branding

- .changeset/quick-meals-live.md
- .changeset/six-mangos-hide.md
- design-system/pkg/src/status-light/StatusLight.tsx
- packages/keystatic/src/app/shell/sidebar.tsx
- packages/keystatic/src/config.tsx
- packages/keystatic/src/reader/github.ts
- packages/keystatic/src/reader/index.ts
Support `ui.navigation` configuration. Minor fixes for `StatusLight` UI component.
> Curated navigation

- docs/keystatic.config.tsx
- docs/src/content/navigation.yaml
- docs/src/content/pages/user-interface.mdoc
- packages/keystatic/src/app/shell/sidebar.tsx
Employ new `ui` config for the docs instance and document its usage.
Wait for #737 to be published.
> Document UI config

- docs/src/content/navigation.yaml
- docs/src/content/pages/recipes/real-time-previews.mdoc
This needs a good review, but I was able to follow my own written steps and get a fresh new Keystatic project working with previews 👍
Needs some clarifications around using this locally vs on a deployed site.
[My attempt](https://github.com/simonswiss/live-previews/tree/main) worked great on the Vercel deployment, but not locally (`github` mode)
> Realtime previews guide

- docs/src/content/pages/recipes/real-time-previews.mdoc
> Fix minor typo in real-time previews recipe

- .changeset/mighty-beds-film.md
- packages/keystatic/src/app/useItemData.ts
> Fix deleting files inside an entry directory that aren't associated with the entry when updating or deleting the entry

- .changeset/lucky-pots-build.md
- .changeset/silent-bulldogs-decide.md
- design-system/pkg/src/button/useActionButtonStyles.tsx
- packages/keystatic/src/app/CollectionPage.tsx
Collection table: hide "status" column for default branch.
> Entry status column

- .changeset/tender-islands-search.md
- packages/keystatic/src/app/ItemPage.tsx
- packages/keystatic/src/app/branch-selection.tsx
Improve error message for branch creation name validation.
> Pretty error for create branch mutation

- docs/src/app/(public)/resources/page.tsx
This makes the Keystatic playlist from the Thinkmill YouTube account show next to every linked video 👍
> Append Keystatic playlist URL param to YouTube links

- docs/src/content/pages/cloud.mdoc
Document addition of shorthand parameters from https://github.com/Thinkmill/keystatic-cloud/pull/122
> Add shorthand parameters to cloud docs

- .changeset/empty-ligers-behave.md
- .changeset/tasty-pillows-think.md
- dev-projects/next-app/keystatic.config.tsx
- docs/src/components/document-renderer.tsx
- docs/src/content/pages/fields/object.mdoc
- packages/keystatic/src/form/api.tsx
- packages/keystatic/src/form/fields/context.tsx
- packages/keystatic/src/form/fields/date/ui.tsx
- packages/keystatic/src/form/fields/datetime/ui.tsx
- packages/keystatic/src/form/fields/file/ui.tsx
- packages/keystatic/src/form/fields/image/ui.tsx
- packages/keystatic/src/form/fields/integer/ui.tsx
- packages/keystatic/src/form/fields/object/ui.tsx
- packages/keystatic/src/form/fields/pathReference/ui.tsx
- packages/keystatic/src/form/fields/relationship/ui.tsx
- packages/keystatic/src/form/fields/select/ui.tsx
- packages/keystatic/src/form/fields/slug/ui.tsx
- packages/keystatic/src/form/fields/text/ui.tsx
- packages/keystatic/src/form/fields/url/ui.tsx
Support "layout" prop on `fields.object()`. Also, add required indicators to relevant fields.
Resolves #669
> Field object layout

- docs/keystatic.config.tsx
- docs/src/app/(public)/resources/page.tsx
- docs/src/content/resources/mini-course-create-a-git-hub-powered-blog-with-keystatic-and-next-js.yaml
> New Keystatic YouTube playlist with playlist block in CMS

- .changeset/violet-icons-hug.md
- packages/astro/src/api.tsx
> Fix astro build error

- .changeset/stupid-chefs-grin.md
- packages/keystatic/src/app/create-item.tsx
> Fix drafts on item creation not being deleted after the item is created

- .changeset/seven-cycles-doubt.md
- packages/keystatic/src/app/shell/data.tsx
- packages/keystatic/src/app/shell/sidebar/components.tsx
- packages/keystatic/src/app/ui.tsx
> Fix url encoding breaking on auth redirects

- .changeset/large-lamps-relax.md
- dev-projects/localization/src/keystatic.config.ts
- dev-projects/next-app/keystatic.config.tsx
- packages/keystatic/src/form/fields/document/DocumentEditor/component-blocks/insertion-and-preview-props.test.tsx
- packages/keystatic/src/form/fields/multiselect/index.tsx
- packages/keystatic/src/form/fields/select/index.tsx
> Improve type inference for `fields.select` and `fields.multiselect`

- .changeset/thirty-tigers-hug.md
- packages/keystatic/src/form/fields/slug/ui.tsx
> Show name fields in slug fields as required if the min length is greater than 0

- .changeset/loud-swans-change.md
- packages/astro/package.json
> Fix `internal` files not being published in astro package

- .changeset/grumpy-falcons-attend.md
- packages/keystatic/src/form/fields/document/DocumentEditor/tests/utils.tsx
- packages/keystatic/src/form/fields/document/markdoc/markdoc.test.tsx
- packages/keystatic/src/form/fields/document/markdoc/to-markdoc.tsx
- packages/keystatic/src/form/fields/markdoc/editor/markdoc/serialize.ts
- packages/keystatic/src/form/fields/markdoc/editor/mdx/serialize.ts
- packages/keystatic/src/form/fields/markdoc/editor/tests/markdoc.test.tsx
- packages/keystatic/src/form/fields/markdoc/editor/tests/mdx.test.tsx
> Fix hard breaks not being serialised in the editors

- .changeset/itchy-drinks-smile.md
- packages/keystatic/src/form/fields/markdoc/editor/custom-components.tsx
This tweaks the UI for the new Markdoc field.
> Tweak Markdoc Editor Component UI

- docs/src/content/pages/format-options.mdoc
Actual `DataFormat` is 'json' | 'yaml'
> fix(docs): invalid JSON doesn't match real type

- docs/src/content/pages/content-components.mdoc
> Update repeating content component docs

- .changeset/breezy-panthers-bake.md
- packages/keystatic/src/form/fields/markdoc/editor/mdx/serialize.ts
- packages/keystatic/src/form/fields/markdoc/editor/schema.tsx
- packages/keystatic/src/form/fields/markdoc/editor/tests/markdoc.test.tsx
- packages/keystatic/src/form/fields/markdoc/editor/tests/mdx.test.tsx
- packages/keystatic/src/form/fields/markdoc/editor/tests/utils.tsx
- packages/keystatic/src/form/fields/markdoc/index.tsx
> Fix tables in `fields.mdx`

- .changeset/weak-windows-design.md
- packages/keystatic/src/form/fields/markdoc/editor/markdoc/parse.ts
- packages/keystatic/src/form/fields/markdoc/editor/props-serialization.ts
- packages/keystatic/src/form/fields/markdoc/editor/tests/markdoc.test.tsx
> Add missing content component fields

- .changeset/fuzzy-olives-remain.md
- packages/keystatic/src/form/fields/markdoc/editor/custom-components.tsx
- packages/keystatic/src/form/fields/markdoc/editor/react-node-views.tsx
- packages/keystatic/src/form/fields/markdoc/editor/schema.tsx
> Fix DOM error when deleting wrapper components in some cases in the new editor

- .changeset/bright-timers-serve.md
- packages/keystatic/src/form/fields/markdoc/editor/Toolbar.tsx
> Fix link button in editor toolbar opening modal when unlinking

- docs/src/content/pages/user-interface.mdoc
> Change keystatic.config.ts in docs example to keystatic.config.tsx where JSX is used

- .changeset/rich-plums-sort.md
- packages/keystatic/src/component-blocks/cloud-image-preview.tsx
- packages/keystatic/src/form/fields/cloudImage/ui.tsx
- packages/keystatic/src/form/fields/slug/ui.tsx
Minor cosmetic improvements to `fields.cloudImage()`, mainly clearer delineation of related fields.
> Cloud image field cosmetic

- docs/src/content/navigation.yaml
- docs/src/content/pages/recipes/astro-images.mdoc
Documents https://github.com/Thinkmill/keystatic/issues/930 and https://github.com/Thinkmill/keystatic/discussions/931
> Astro images guide: standalone images and content components

- .changeset/clean-years-return.md
- packages/keystatic/src/app/shell/data.tsx
- packages/keystatic/src/app/shell/index.tsx
> Show message when a branch is selected that doesn't exist in the repository

- docs/src/content/projects/spacebring.mdoc
We use Keystatic to manage all the content of our website. The PR is missing the cover URL though, I had no luck with permissions to upload it.
> Add Spacebring to showcase

- .changeset/shiny-peaches-approve.md
- .changeset/tricky-days-type.md
- packages/keystatic/package.json
- packages/keystatic/src/app/ui-empty.tsx
- packages/keystatic/src/form/fields/empty-field-ui.tsx
- packages/keystatic/src/form/fields/markdoc/index.tsx
- packages/keystatic/src/form/fields/markdoc/ui.tsx
- packages/keystatic/src/ui.tsx
Fixes #1121 (since the yjs packages are no longer imported on the server)
Fixes #1112
> Optimise server side bundle

- .changeset/perfect-boxes-matter.md
- packages/keystatic/src/form/fields/blocks/ui.tsx
> Add missing space in add block dialog

- .changeset/dry-keys-travel.md
- design-system/pkg/package.json
- packages/next/package.json
> Fix peer dependency on Next being fixed to a single version

- .changeset/orange-turkeys-scream.md
- docs/keystatic.config.tsx
- docs/src/content/pages/reader-api.mdoc
- packages/keystatic/src/form/fields/markdoc/editor/markdoc/serialize.ts
- packages/keystatic/src/form/fields/markdoc/editor/mdx/serialize.ts
- packages/keystatic/src/form/fields/markdoc/editor/serialize-inline.ts
- packages/keystatic/src/form/fields/markdoc/editor/tests/docs.test.ts
- packages/keystatic/src/form/fields/markdoc/editor/tests/markdoc.test.tsx
- packages/keystatic/src/form/fields/markdoc/editor/tests/mdx.test.tsx
> Improve mark printing in the new editor

- .changeset/grumpy-apricots-obey.md
- .changeset/mean-pumpkins-float.md
- dev-projects/next-app/next.config.js
- dev-projects/remix/package.json
- docs/next.config.js
- docs/src/content/pages/configuration.mdoc
- docs/src/content/pages/fields/array.mdoc
- docs/src/content/pages/format-options.mdoc
- docs/src/content/pages/installation-astro.mdoc
- docs/src/content/pages/installation-next-js.mdoc
- docs/src/content/pages/installation-remix.mdoc
- docs/src/content/pages/recipes/nextjs-disable-admin-ui-in-production.mdoc
- packages/remix/package.json
- pnpm-lock.yaml
- templates/astro/keystatic.config.ts
- templates/nextjs/app/[slug]/layout.tsx
- templates/nextjs/app/[slug]/page.tsx
- templates/nextjs/keystatic.config.ts
- templates/nextjs/next.config.js
- templates/nextjs/package.json
- templates/remix/app/root.tsx
- templates/remix/app/routes/_index.tsx
- templates/remix/app/routes/posts.$slug.tsx
- templates/remix/app/styles/styles.css
- templates/remix/keystatic.config.ts
- templates/remix/package.json
- templates/remix/remix.config.js
- templates/remix/remix.env.d.ts
- templates/remix/tsconfig.json
- templates/remix/vite.config.js
> Replace references to the document field with references to the markdoc field in docs and templates

- .changeset/nine-kiwis-teach.md
- babel.config.json
> Fix some overlays not showing

- .changeset/khaki-dragons-punch.md
- packages/keystatic/src/app/shell/data.tsx
- packages/keystatic/src/app/shell/empty-repo.tsx
> Show specific error when Git repo is not initialised

- .changeset/olive-parents-warn.md
- packages/keystatic/src/form/fields/markdoc/editor/popovers/index.tsx
> Show mark toolbar for the deepest mark rather than the one first found in `fields.markdoc`/`fields.mdx`

- .changeset/hip-houses-hope.md
- docs/src/components/fields/file.tsx
- docs/src/components/fields/image.tsx
- packages/keystatic/src/form/fields/file/index.tsx
- packages/keystatic/src/form/fields/file/ui.tsx
- packages/keystatic/src/form/fields/image/index.tsx
- packages/keystatic/src/form/fields/image/ui.tsx
- packages/keystatic/src/form/fields/markdoc/config.ts
- packages/keystatic/src/form/fields/markdoc/editor/images.tsx
- packages/keystatic/src/form/fields/markdoc/editor/schema.tsx
> Add `transformFilename` option to `fields.image`/`fields.file`/image options in `fields.markdoc`/`fields.mdx`

- .changeset/eighty-parents-end.md
- docs/src/content/navigation.yaml
- docs/src/content/pages/fields/ignored.mdoc
- packages/keystatic/src/form/fields/ignored.tsx
- packages/keystatic/src/form/fields/index.ts
> Add `fields.ignored`

- docs/src/app/mailing-list/route.ts
- docs/src/components/forms/mailing-list.tsx
Updates tags applied to Buttondown API requests to conform to updated naming convention and length requirements.
> Update Buttondown Newsletter Tags

- .changeset/unlucky-pears-eat.md
- packages/keystatic/src/app/l10n/es-ES/basedOn/index.json
- packages/keystatic/src/app/l10n/es-ES/branchName/index.json
- packages/keystatic/src/app/l10n/es-ES/branches/index.json
- packages/keystatic/src/app/l10n/es-ES/createPullRequest/index.json
- packages/keystatic/src/app/l10n/es-ES/newBranch/index.json
- packages/keystatic/src/app/l10n/es-ES/otherBranches/index.json
- packages/keystatic/src/app/l10n/es-ES/pullRequests/index.json
- packages/keystatic/src/app/l10n/es-ES/save/index.json
- packages/keystatic/src/app/l10n/es-ES/singleton/index.json
- packages/keystatic/src/app/l10n/es-ES/singletons/index.json
- packages/keystatic/src/app/l10n/es-ES/theCurrentlyCheckedOutBranch/index.json
- packages/keystatic/src/app/l10n/es-ES/theDefaultBranchInYourRepository/index.json
- packages/keystatic/src/app/l10n/es-ES/viewPullRequests/index.json
Improves spanish translation values. 
(I'm a native spanish speaker)
> i18n: improve spanish values
